wangkanai/wangkanai

sample/Device/Controllers/HomeController.cs
sample/Device/Views/Home/Index.cshtml
sample/Device/Views/Shared/_Layout.cshtml
sample/Device/Views/_ViewImports.cshtml
src/Wangkanai.Detection.Device/DeviceTagHelper.cs
src/Wangkanai.Detection.Device/TagHelpers/DeviceTagHelper.cs
src/Wangkanai.Detection.Device/Wangkanai.Detection.Device.csproj

adding concept, but on the razor page the Tag is not lighting up.

Device Taghelper (#23)

---

src/Wangkanai.Detection/DetectionService.cs
test/Wangkanai.Detection.Test/DetectionServiceTests.cs

Add DetectionService.cs tests and DetectionService.cs refactoring. 
Related to (#27)

Add DetectionService.cs tests and DetectionService.cs refactoring.

---

test/Wangkanai.Detection.Test/DetectionServiceCollectionExtensionsTests.cs
test/Wangkanai.Detection.Test/Wangkanai.Detection.Test.csproj

Add DetectionServiceCollectionExtensionsTests.cs. Updating dependencies.
Related to (#27)

Add DetectionServiceCollectionExtensionsTests.cs. Updating dependencies.

---

test/Wangkanai.Detection.Test/UserAgentTests.cs
test/Wangkanai.Detection.Test/VersionTests.cs

Add UserAgentTests.cs and VersionTests.cs 
Related to (#27)

Add UserAgentTests.cs and VersionTests.cs

---

test/Wangkanai.Detection.Test/VersionTests.cs

Updating VersionTests.cs 
Related to (#34) and (#27)

Updating VersionTests.cs.

---

README.md
sample/Browser/Startup.cs
sample/Device/Startup.cs
sample/Engine/Startup.cs
sample/Platform/Startup.cs
sample/Sandbox/Controllers/HomeController.cs
sample/Sandbox/Startup.cs
sample/Sandbox/Views/Home/Index.cshtml
src/Wangkanai.Detection.Browser/BrowserBuilderExtensions.cs
src/Wangkanai.Detection.Core/Abstractions/IDetectionCoreBuilder.cs
src/Wangkanai.Detection.Core/Builder/DetectionCoreBuilder.cs
src/Wangkanai.Detection.Core/DetectionCoreCollectionExtensions.cs
src/Wangkanai.Detection.Core/DetectionService.cs
src/Wangkanai.Detection.Crawler/Abstractions/ICrawler.cs
src/Wangkanai.Detection.Crawler/Abstractions/ICrawlerResolver.cs
src/Wangkanai.Detection.Crawler/BotComparer.cs
src/Wangkanai.Detection.Crawler/Crawler.cs
src/Wangkanai.Detection.Crawler/CrawlerBuilderExtensions.cs
src/Wangkanai.Detection.Crawler/CrawlerResolver.cs
src/Wangkanai.Detection.Crawler/CrawlerType.cs
src/Wangkanai.Detection.Device/DeviceBuilderExtensions.cs
src/Wangkanai.Detection.Engine/EngineBuilderExtensions.cs
src/Wangkanai.Detection.Platform/PlatformBuilderExtensions.cs
src/Wangkanai.Detection/DetectionCollectionExtensions.cs
test/Wangkanai.Detection.Crawler.Test/CrawlerResolverTest.cs
test/Wangkanai.Detection.Test/DetectionCoreollectionExtensionsTests.cs

add the global AddDetection() as new entry point #59

refactor orginal AddDetection() to AddDetectionCore()

---

README.md
sample/Sandbox/Controllers/HomeController.cs
sample/Sandbox/Views/Home/Index.cshtml
sample/Sandbox/Views/Shared/_Layout.cshtml
src/Wangkanai.Detection.Browser/BrowserResolver.cs
src/Wangkanai.Detection.Core/Abstractions/IUserAgentService.cs
src/Wangkanai.Detection.Core/DetectionCoreCollectionExtensions.cs
src/Wangkanai.Detection.Core/UserAgentService.cs
src/Wangkanai.Detection.Crawler/CrawlerResolver.cs
src/Wangkanai.Detection.Device/DeviceResolver.cs
src/Wangkanai.Detection.Engine/Abstractions/IEngine.cs
src/Wangkanai.Detection.Engine/Engine.cs
src/Wangkanai.Detection/Detection.cs
src/Wangkanai.Detection/DetectionCollectionExtensions.cs
src/Wangkanai.Detection/IDetection.cs
test/Wangkanai.Detection.Browser.Test/BrowserResolverTests.cs
test/Wangkanai.Detection.Crawler.Test/CrawlerTest.cs
test/Wangkanai.Detection.Device.Test/DeviceTestAbstract.cs
test/Wangkanai.Detection.Test/DetectionCoreollectionExtensionsTests.cs
test/Wangkanai.Detection.Test/DetectionServiceTests.cs

#64 track global detection service feature

add global detection

---

src/Wangkanai.Detection.Browser/Abstractions/IBrowser.cs
src/Wangkanai.Detection.Browser/Browser.cs
src/Wangkanai.Detection.Browser/BrowserResolver.cs
src/Wangkanai.Detection.Core/Abstractions/IManufacturer.cs
src/Wangkanai.Detection.Crawler/CrawlerResolver.cs
src/Wangkanai.Detection.Device/DeviceResolver.cs
src/Wangkanai.Detection.Engine/Abstractions/IEngine.cs
src/Wangkanai.Detection.Platform/Platform.cs
src/Wangkanai.Detection.Platform/PlatformResolver.cs

- Refactor Resolver to return interface of all implementation

Add IManufacturer interface to base #71

---

src/Wangkanai.Detection.Browser/BrowserResolver.cs

Reordered browser detection sequence.

Fixed chrome detection

---

src/Wangkanai.Detection.Core/UserAgent.cs
src/Wangkanai.Detection.Core/UserAgentService.cs
test/Wangkanai.Detection.Browser.Test/BrowserResolverTests.cs
test/Wangkanai.Detection.Test/UserAgentTests.cs

Why would the UserAgent be null? this is the web standard and also it in the test coverage that i wrote. 
#73 #76 
Please answer my question before I merge this pull request.

make except useragent null to empty string

---

test/Wangkanai.Detection.Crawler.Test/CrawlerTest.cs

#86 crawler Resolver check null && empty useragent

---

Responsive/src/ResponsiveCollectionExtensions.cs
sample/Responsive/Startup.cs

refactor responsive collection extensions

---

sample/Responsive/Startup.cs
src/Detection.Core/src/Builders/DetectionBuilder.cs
src/Detection.Core/src/Builders/DetectionCoreBuilder.cs
src/Detection.Core/src/DetectionCoreCollectionExtensions.cs
src/Detection/src/DetectionCollectionExtensions.cs
src/Responsive.Core/src/Abstractions/IResponsiveCoreBuilder.cs
src/Responsive.Core/src/Abstractions/IResponsiveOptionsBuilder.cs
src/Responsive.Core/src/ApplicationBuilderExtensions.cs
src/Responsive.Core/src/Builders/ResponsiveApplicationBuilderExtensions.cs
src/Responsive.Core/src/Builders/ResponsiveBuilder.cs
src/Responsive.Core/src/Builders/ResponsiveCoreBuilder.cs
src/Responsive.Core/src/Builders/ResponsiveOptionsBuilder.cs
src/Responsive.Core/src/Exceptions/ResponsiveBuilderArgumentNullException.cs
src/Responsive.Core/src/Exceptions/ResponsiveCoreBuilderArgumentNullException.cs
src/Responsive.Core/src/ResponsiveCoreCollectionExtensions.cs
src/Responsive.Core/src/ResponsiveOptionsBuilderExtensions.cs
src/Responsive.Core/src/ViewBuilderExtensions.cs
src/Responsive.Core/test/ApplicationBuilderExtensionsTests.cs
src/Responsive/src/ResponsiveCollectionExtensions.cs
src/Responsive/test/ResponsiveBuilderTests.cs
src/Responsive/test/ResponsiveCollectionExtensionsTests.cs

#111 refactor `AddResponsive()` to `AddResponsiveCore()`

ResponsiveCore refactoring

---

src/Detection.Browser/src/Collections/Chrome.cs
src/Detection.Browser/test/BrowserResolverTests.cs
src/Detection.Browser/test/Collections/ChromeTests.cs
src/Detection.Crawler/test/CrawlerTest.cs

(fix) #121 Yandex bot is crashing IDetection creation

---

sample/Detection/Detection.csproj
sample/Detection/Views/Home/Index.cshtml
sample/Responsive/Controllers/HomeController.cs
sample/Responsive/Program.cs
sample/Responsive/Responsive.csproj
sample/Responsive/Startup.cs
sample/Responsive/Views/Home/Index.cshtml
sample/Responsive/Views/Home/Index.mobile.cshtml
sample/Responsive/Views/Shared/_Layout.cshtml
sample/Responsive/Views/Shared/_Layout.mobile.cshtml
sample/Responsive/Views/Shared/_Layout.tablet.cshtml
sample/Responsive/Views/Shared/_TagHelper.cshtml
sample/Responsive/Views/_ViewImports.cshtml
sample/Responsive/libman.json
src/Responsive.TagHelper/src/BrowserTagHelper.cs
src/Responsive.TagHelper/src/DeviceTagHelper.cs

Responsive

---

src/Detection.Core/src/UserAgent.cs

#120 fixed default useragent is null

---

src/Detection.Device/src/TabletCollection.cs
src/Detection.Device/test/DeviceTabletTest.cs

#116 fixed Amazon Fire detecting as Desktop

---

src/Detection.Browser/src/Abstractions/IBrowserResolver.cs
src/Detection.Browser/src/BrowserResolver.cs
src/Detection.Browser/src/Collections/Firefox.cs
src/Detection.Browser/test/BrowserResolverTests.cs
src/Detection.Core/src/DetectionVersionExtensions.cs

#89 fixed BlackBerry version fail

---

src/Detection.Browser/src/Browser.cs
src/Detection.Browser/src/Collections/Chrome.cs
src/Detection.Browser/src/Collections/Edge.cs
src/Detection.Browser/src/Collections/Firefox.cs
src/Detection.Browser/src/Collections/InternetExplorer.cs
src/Detection.Browser/src/Collections/Opera.cs
src/Detection.Browser/src/Collections/Safari.cs

Ref #122 refactor and better fixed

fixed yandex bot

---

Detection.sln
appveyor.yml
dotnet-install.ps1
run.ps1
sample/Responsive/Startup.cs
src/Responsive.Core/src/Builders/ResponsiveApplicationBuilderExtensions.cs
src/Responsive.Core/src/Builders/ResponsiveOptionsBuilderExtensions.cs
src/Responsive.Core/src/CookieManager.cs
src/Responsive.Core/src/ResponsiveOptions.cs
src/Responsive.Core/test/ApplicationBuilderExtensionsTests.cs
src/Responsive.Core/test/CookieManagerTest.cs
src/Responsive.Core/test/DeviceHttpContextExtensionsTests.cs
src/Responsive.Core/test/ResolverManagerTests.cs
src/Responsive.Core/test/ResponsiveMiddlewareTests.cs
src/Responsive.Core/test/ResponsiveTestAbstract.cs
src/Responsive.Core/test/ResponsiveViewLocationExpanderTests.cs
src/Responsive.Core/test/UserPreferenceTest.cs

Responsive Option

---

sample/Responsive/Startup.cs
src/Responsive.Core/src/Abstractions/IResponsiveOptions.cs
src/Responsive.Core/src/Builders/ApplicationBuilderExtensions.cs
src/Responsive.Core/src/Builders/ResponsiveOptions.cs
src/Responsive.Core/src/CookieManager.cs
src/Responsive.Core/src/Extensions/StringExtensions.cs
src/Responsive.Core/src/ResolverManager.cs
src/Responsive.Core/src/ResponsiveCoreCollectionExtensions.cs
src/Responsive.Core/src/ResponsiveMiddleware.cs
src/Responsive.Core/test/ResolverManagerTests.cs
src/Responsive/src/ResponsiveCollectionExtensions.cs

add option configuration service

---

src/Detection.Browser/src/Wangkanai.Detection.Browser.csproj
src/Detection.Core/src/Wangkanai.Detection.Core.csproj
src/Detection.Crawler/src/Wangkanai.Detection.Crawler.csproj
src/Detection.Device/src/Wangkanai.Detection.Device.csproj
src/Detection.Engine/src/Wangkanai.Detection.Engine.csproj
src/Detection.Platform/src/Wangkanai.Detection.Platform.csproj
src/Detection/src/Wangkanai.Detection.csproj
src/Responsive.Core/src/Wangkanai.Responsive.Core.csproj
src/Responsive.TagHelper/src/Wangkanai.Responsive.TagHelper.csproj
src/Responsive/src/Wangkanai.Responsive.csproj

remove generate package on build in csproj

---

sample/Responsive/Controllers/HomeController.cs
sample/Responsive/Views/Home/Index.cshtml
sample/Responsive/Views/Home/Index.mobile.cshtml
sample/Responsive/Views/Home/Index.tablet.cshtml
sample/Responsive/Views/Home/Mobile/Index.cshtml
sample/Responsive/Views/Home/Tablet/Index.cshtml
src/Detection.Browser/test/BrowserNotFoundExceptionTest.cs
src/Detection.Core/src/BaseResolver.cs
src/Detection.Core/src/UserAgent.cs
src/Detection.Core/src/UserAgentService.cs
src/Detection.Device/test/DeviceNotFoundExceptionTest.cs
src/Detection/src/IDetection.cs
src/Responsive.Core/test/ResponsiveMiddlewareTests.cs
src/Responsive/test/ResponsiveCollectionExtensionsTests.cs

return back detection interface

---

src/Responsive.Core/src/ResponsiveCoreCollectionExtensions.cs
src/Responsive.Core/src/Wangkanai.Responsive.Core.csproj

responsive for all detection features

---

README.md

release 2.0

---

README.md

fixed link mistake

---

README.md
sample/Responsive/Startup.cs

update readme and sample

---

README.md
src/Responsive.Core/src/ResponsiveViewLocationExpander.cs

Viewlocation

---

src/Detection.Browser/src/Exceptions/BrowserNotFoundException.cs
src/Detection.Core/src/Abstractions/IResolver.cs
src/Detection.Core/src/Abstractions/IUserAgent.cs
src/Detection.Core/src/BaseResolver.cs
src/Detection.Core/src/Models/UserAgent.cs
src/Detection.Core/src/Services/Defaults/UserAgentService.cs
src/Detection.Core/src/Services/IUserAgentService.cs
src/Responsive.Core/test/ResponsiveMiddlewareTests.cs

remove interface from user agent

---

src/Detection.Browser/src/Collections/InternetExplorer.cs
src/Detection.Browser/src/Models/BrowserFactory.cs
src/Detection.Core/src/DependencyInjection/ApplicationBuilderExtensions.cs
src/Detection.Core/src/DependencyInjection/CoreCollectionExtensions.cs
src/Detection.Core/src/Extensions/DetectionVersionExtensions.cs
src/Detection.Core/test/DependencyInjection/ApplicationBuilderExtensionsTest.cs
src/Detection.Core/test/Extensions/DetectionVersionExtensionsTest.cs
src/Detection.Crawler/src/Models/CrawlerFactory.cs
src/Detection.Crawler/test/CrawlerTest.cs
src/Responsive.Core/src/DependencyInjection/ApplicationBuilderExtensions.cs
src/Responsive.Core/test/DependencyInjection/ApplicationBuilderExtensionsTests.cs

refactor and add application builder extensions to check marker service

Extensions

---

src/Detection.Core/src/Internal/DetectionMarkerService.cs
src/Responsive.Core/src/Internal/ResponsiveMarkerService.cs

This an internal resource to validate that the service has been added correctly

change marker service to internal

---

src/Responsive.Core/src/DependencyInjection/CoreCollectionExtensions.cs
src/Responsive.Core/src/DependencyInjection/IResponsiveCoreBuilder.cs
src/Responsive.Core/src/DependencyInjection/ResponsiveCoreBuilder.cs

init add responsive core

---

README.md

marked 3.0 for asp.net core 3.0 in nuget release badges

---

src/Detection.Core/test/DependencyInjection/ApplicationBuilderExtensionsTest.cs
src/Responsive.Core/src/DependencyInjection/ApplicationBuilderExtensions.cs
src/Responsive.Core/test/DependencyInjection/ApplicationBuilderExtensionsTests.cs
src/Responsive/test/ResponsiveBuilderTests.cs

fixed borken failed test
because reference the wrong logging factory library
Castle.Core.Logging => Microsoft.Extensions.Logging

fixed borken failed test

---

appveyor.yml

add merges to ci build

---

src/Engine/IEngineFactory.cs
src/Engine/Models/Engine.cs
src/Engine/Models/EngineFactory.cs
test/Browser/BrowserClassTests.cs
test/Browser/BrowserNotFoundExceptionTest.cs
test/Browser/BrowserResolverTests.cs
test/Client.cs
test/Crawler/CrawlerTest.cs
test/DependencyInjection/CoreCollectionExtensionsTests.cs
test/DetectionCoreollectionExtensionsTests.cs
test/Device/DeviceDesktopTest.cs
test/Device/DeviceMobileTest.cs
test/Device/DeviceNotFoundExceptionTest.cs
test/Device/DeviceTabletTest.cs
test/Device/DeviceTest.cs
test/Device/DeviceTestAbstract.cs
test/Engine/EngineTest.cs
test/Models/VersionTests.cs
test/Platform/PlatformTest.cs
test/Responsive/DeviceHttpContextExtensionsTests.cs
test/Responsive/ResolverManagerTests.cs
test/Responsive/ResponsiveCollectionExtensionsTests.cs
test/Responsive/ResponsiveMiddlewareTests.cs
test/Responsive/ResponsiveViewLocationExpanderTests.cs
test/Responsive/UserPreferenceTest.cs
test/UserAgentCollection.cs

init Engine feature into detectuin

---

src/DependencyInjection/ApplicationBuilderExtensions.cs
src/DependencyInjection/BuilderExtensions/CoreBuilderExtensions.cs
src/DependencyInjection/DetectionCollectionExtensions.cs
src/Services/Defaults/DefaultCrawlerService.cs
test/DependencyInjection/CoreCollectionExtensionsTests.cs
test/Services/CrawlerServiceTest.cs

Add reiterate through all in enum of crawler

---

src/BaseResolver.cs

fixed typo

---

src/DependencyInjection/DetectionCollectionExtensions.cs
src/Depreciated/DeviceFactory.cs
src/Depreciated/DeviceResolver.cs
src/Depreciated/IDeviceFactory.cs
src/Depreciated/IDeviceResolver.cs
src/Extensions/DeviceExtensions.cs
src/Hosting/ResponsiveMiddleware.cs
src/Responsive/ResolverManager.cs
src/Responsive/ResponsiveViewLocationExpander.cs
src/Services/Defaults/DeviceService.cs
src/TagHelpers/DeviceTagHelper.cs
test/Hosting/ResponsiveMiddlewareTests.cs

Do some refactoring with Rider

---

src/DependencyInjection/BuilderExtensions/Responsive.cs
src/DependencyInjection/DetectionCollectionExtensions.cs
src/Exceptions/BrowserNotFoundException.cs
src/Exceptions/DeviceNotFoundException.cs
src/Exceptions/GetDeviceArgumentNullException.cs
src/Extensions/DeviceExtensions.cs
src/Extensions/HttpContextExtensions.cs
src/Extensions/UserAgentExtensions.cs
src/Extensions/VersionExtensions.cs
test/DependencyInjection/ApplicationBuilderExtensionsTest.cs
test/Hosting/ResponsiveMiddlewareTests.cs
test/Services/MockService.cs

Refactor user agent extensions

---

src/Extensions/UserAgentExtensions.cs
src/Services/Defaults/PlatformService.cs
test/Services/PlatformServiceTest.cs

Add all operating system in the platform resolver

---

src/Extensions/UserAgentExtensions.cs
src/Extensions/VersionExtensions.cs
src/Services/Defaults/CrawlerService.cs
src/Services/Defaults/PlatformService.cs
test/Services/PlatformServiceTest.cs

Refactor crawler service

---

src/Models/Device.cs
src/Services/Defaults/DeviceService.cs
test/Services/DeviceServiceTest.cs

Add TV device detection

---

src/Extensions/EnumExtensions.cs
src/Extensions/UserAgentExtensions.cs
test/Extensions/UserAgentExtensionsTest.cs

Enum flags

---

src/Extensions/EnumExtensions.cs
src/Extensions/UserAgentExtensions.cs
test/Extensions/UserAgentExtensionsTest.cs

Refactor enum extensions

---

src/Services/PlatformService.cs
test/Services/PlatformServiceTest.cs

Fix windows x64 using WOW64

---

Detection.sln.DotSettings
sample/Detection/Views/Home/Index.cshtml
src/Extensions/UserAgentExtensions.cs
src/Models/Crawler.cs
src/Models/Engine.cs
src/Models/OperatingSystem.cs
src/Services/BrowserService.cs
src/Services/EngineService.cs
src/Services/Interfaces/IBrowserService.cs
src/Services/Interfaces/IDetectionService.cs
src/Services/Interfaces/IEngineService.cs
src/Services/PlatformService.cs
test/Browser/BrowserResolverTests.cs
test/Extensions/UserAgentExtensionsTest.cs
test/Services/EngineServiceTest.cs
test/Services/PlatformServiceTest.cs

```csharp
public enum Engine
{
Unknown    = 0,       // Unknown engine
WebKit     = 1,       // iOs (Safari, WebViews, Chrome <28) (https://webkit.org/)
Blink      = 1 << 1,  // Google Chrome, Opera v15+ (https://www.chromium.org/Home)
Gecko      = 1 << 2,  // Firefox, Netscape (https://hg.mozilla.org/mozilla-central/)
Trident    = 1 << 3,  // IE, Outlook
EdgeHTML   = 1 << 4,  // Microsoft Edge
Servo      = 1 << 5,  // Mozilla & Samsung (https://github.com/servo/servo)
Others     = 1 << 6   // Others
}
```

Engine Resolver functional and unit tests all pass

---

Detection.sln.DotSettings
src/Models/Crawler.cs
src/Models/Device.cs
src/Models/Engine.cs
src/Models/OperatingSystem.cs
test/Models/UserAgentTests.cs
test/Models/VersionTests.cs
test/Services/CrawlerServiceTest.cs
test/Services/DetectionServiceTests.cs

```csharp
[Flags]
public enum Device
{
Desktop = 0,      // Windows, Mac, Linux
Tablet  = 1 << 0, // iPad, Android
Mobile  = 1 << 1, // iPhone, Android
Tv      = 1 << 2, // Samsung, LG
Console = 1 << 3, // XBox, Play Station
Car     = 1 << 4, // Ford, Toyota
IoT     = 1 << 5  // Raspberry Pi
}
```

Reformat using code style

---

test/Services/CrawlerServiceTest.cs
test/Services/EngineServiceTest.cs

Ref #121 to make sure it working fine.

Yandex bot unit test

---

Detection.sln.DotSettings

rider code style for c#

---

src/Services/DeviceService.cs

Make the code more read able and more future maintain able.

Refactor Device Resolver

---

sample/Detection/Views/Home/Index.cshtml
src/Extensions/HttpContextExtensions.cs
src/Extensions/UserAgentExtensions.cs
src/Services/BrowserService.cs
src/Services/CrawlerService.cs
src/Services/EngineService.cs
src/Services/Interfaces/IBrowserService.cs
src/Services/PlatformService.cs
src/Services/UserAgentService.cs
src/TagHelpers/DeviceTagHelper.cs
test/Services/BrowserServiceTest.cs

Add Version parse to Browser Resolver

---

appveyor.yml
sample/Responsive/Views/Home/Mobile/Index.cshtml
sample/Responsive/Views/Home/Tablet/Index.cshtml

Fixed the taghelper mistake in the sample responsive web app

---

src/DependencyInjection/ApplicationBuilderExtensions.cs
src/DependencyInjection/BuilderExtensions/Core.cs
src/Extensions/HttpContextExtensions.cs

Working across requests in session.

---

src/Areas/Detection/Controllers/PreferenceController.cs
src/DependencyInjection/BuilderExtensions/Core.cs
src/DependencyInjection/BuilderExtensions/Responsive.cs
src/DependencyInjection/DetectionCollectionExtensions.cs
src/Extensions/HttpContextExtensions.cs
src/Services/Interfaces/IPreferenceService.cs
src/Services/PreferenceService.cs
src/Services/ResponsiveService.cs
src/TagHelpers/PreferenceTagHelper.cs
test/DependencyInjection/BuilderExtensions/ResponsiveTests.cs
test/Hosting/PreferenceSessionTests.cs
test/Hosting/ResponsiveMiddlewareTests.cs
test/HttpRequestMessageExtensions.cs
test/Services/MockService.cs
test/Wangkanai.Detection.Test.csproj

Preference Service is persistence only to desktop
Causing failing unit tests.

Preference Service is persistence

---

src/Models/Device.cs

How can smart watch be leave out?

Add Smart Watch to device

---

src/DependencyInjection/Options/CrawlerOptions.cs
src/DependencyInjection/Options/DetectionOptions.cs

DetectionOptions add tooltips information

---

src/Hosting/PreferenceController.cs

Controller Area const name

---

src/Extensions/EnumerableExtensions.cs

Refactor IEnumerableExtensions

---

src/DependencyInjection/DetectionCollectionExtensions.cs

Make the  return `IDetectionBuilder` from adding the services more usable.

Refactor Detection Collection Extensions

---

src/DependencyInjection/BuilderExtensions/Responsive.cs
src/Extensions/HttpContextExtensions.cs
src/Hosting/ViewLocationExpander.cs
src/Services/PreferenceService.cs

Inprove the concept of preference service

---

src/DependencyInjection/ApplicationBuilderExtensions.cs
src/DependencyInjection/BuilderExtensions/Core.cs
src/DependencyInjection/BuilderExtensions/Responsive.cs
src/DependencyInjection/Options/ResponsiveOptions.cs

```csharp
public void ConfigureServices(IServiceCollection services)
{
// Add responsive services.
services.AddDetection(options =>
{
options.Responsive.WebApiPath = "/MyApi";
});
// Add framework services.
services.AddControllersWithViews();
}
```

Web Api Path Convention Customize able with DetectionOptions

---

src/Services/Interfaces/IResponsiveService.cs
src/Services/ResponsiveService.cs
src/TagHelpers/PreferenceTagHelper.cs

`ResponsiveService.HasPreferred();` change from `ResponsiveService.IsPreferred();`
This make the method name mean what it should be doing.

Refactor ResponsiveService for better clean code

---

src/Wangkanai.Detection.csproj

```xml
<ItemGroup>
<None Include="..\README.md" />
</ItemGroup>
```

Nuget package documentation fixed readme path

---

sample/Responsive/Views/Home/Index.cshtml
sample/Responsive/Views/Home/Index.mobile.cshtml
sample/Responsive/Views/Home/Index.tablet.cshtml
sample/Responsive/Views/Home/Mobile/Index.cshtml
sample/Responsive/Views/Home/Tablet/Index.cshtml
src/TagHelpers/BrowserTagHelper.cs
src/TagHelpers/DeviceTagHelper.cs

```html
<section id="browser">
<h4>google chrome</h4>
<browser include="chrome">is chrome</browser>
<browser exclude="chrome">not chrome</browser>
<h4>microsoft edge</h4>
<browser include="edge">is edge</browser>
<browser exclude="edge">not edge</browser>
</section>
```

Add browser taghelper

---

src/DependencyInjection/DetectionCollectionExtensions.cs

Reformat comment

---

appveyor.yml

Add deploy github package

---

appveyor.yml

Github Package

---

README.md
src/DependencyInjection/ApplicationBuilderExtensions.cs
src/DependencyInjection/DetectionCollectionExtensions.cs
src/DependencyInjection/Options/ResponsiveOptions.cs
src/Hosting/ViewLocationExpander.cs

Refactor away for clean code

---

src/Extensions/HttpContextExtensions.cs
src/Hosting/PreferenceController.cs
src/Services/CrawlerService.cs
src/Services/ResponsiveService.cs
src/TagHelpers/BrowserTagHelper.cs
src/TagHelpers/CrawlerTagHelper.cs
src/TagHelpers/DeviceTagHelper.cs
src/TagHelpers/EngineTagHelper.cs
src/TagHelpers/PlatformTagHelper.cs
src/TagHelpers/PreferenceTagHelper.cs
test/Mocks/MockService.cs

Finally got this out from the warning list.

Fixed all nullable error in code using c# 8.0

---

.github/pull_request_template.md
appveyor.yml

just focus on building version

---

test/Hosting/ResponsiveMiddlewareTests.cs
test/Mocks/MockService.cs
test/Services/BrowserServiceTest.cs
test/Services/CrawlerServiceTest.cs
test/Services/DetectionServiceTests.cs
test/Services/DeviceServiceTest.cs
test/Services/EngineServiceTest.cs
test/Services/PlatformServiceTest.cs
test/Services/ResponsiveServiceTest.cs

```csharp
public static BrowserService CreateBrowserService(string agent)
=> CreateBrowserService(CreateUserAgentService(agent));
private static BrowserService CreateBrowserService(IUserAgentService agent)
{
var platform = CreatePlatformService(agent);
var engine   = CreateEngineService(agent);
return new BrowserService(agent, platform, engine);
}
```

Mock Service for Continuous Testing

---

.github/workflows/dotnetcore.yml

Build only if pull request and main branches.

Build CI on Windows, Ubuntu, macOS

---

.editorconfig
src/Wangkanai.Detection.csproj

Code Clean up

---

src/DependencyInjection/BuilderExtensions/Responsive.cs
src/Hosting/ResponsivePageMatcherPolicy.cs
src/Hosting/ResponsivePageRouteModelConvention.cs
src/Hosting/ViewLocationExpander.cs
src/IResponsiveMetadata.cs
src/ResponsiveAttribute.cs

I would like to honor code pull request of this work to @rynowak for his contribution. 
If not by his contribution, I would not be able to solve issue #115 on getting responsive to work with razor pages.
Thank you very much. I really appreciate your help.

Responsive for Razor Pages

---

src/Hosting/PageRouteModelConvention.cs

Need to add unit tests and refactor later

Working concept with responsive razor pages using areas

---

README.md
src/DependencyInjection/BuilderExtensions/Responsive.cs

This is better for my preference in the editor

Update README.md with code block hightlight

---

sample/Detection/Areas/Admin/Controllers/ReportController.cs
sample/Detection/Areas/Admin/Pages/Index.cshtml
sample/Detection/Areas/Admin/Pages/Index.mobile.cshtml
sample/Detection/Areas/Admin/Pages/Index.tablet.cshtml
sample/Detection/Areas/Admin/Pages/_ViewStart.cshtml
sample/Detection/Areas/Admin/Views/Report/Index.cshtml
sample/Detection/Areas/Admin/Views/Report/Index.mobile.cshtml
sample/Detection/Areas/Admin/Views/Report/Index.tablet.cshtml
sample/Detection/Areas/Admin/Views/Shared/_AdminLayout.cshtml
sample/Detection/Areas/Admin/Views/Shared/_AdminLayout.mobile.cshtml
sample/Detection/Areas/Admin/Views/Shared/_AdminLayout.tablet.cshtml
sample/Detection/Areas/Admin/Views/Shared/_AdminNavigation.cshtml
sample/Detection/Areas/Admin/Views/Shared/_AdminNavigation.mobile.cshtml
sample/Detection/Areas/Admin/Views/Shared/_AdminNavigation.tablet.cshtml
sample/Detection/Areas/Admin/Views/_ViewImports.cshtml
sample/Detection/Areas/Admin/Views/_ViewStart.cshtml
sample/Detection/Startup.cs
sample/Detection/Views/Shared/_Navigation.cshtml
sample/Detection/Views/Shared/_Navigation.mobile.cshtml
sample/Detection/Views/Shared/_Navigation.tablet.cshtml
sample/Detection/wwwroot/css/site.css

Areas with Responsive Views and Pages

---

README.md
src/DependencyInjection/ApplicationBuilderExtensions.cs

Pipeline validation that Routing is added after detection

---

benchmark/Program.cs
benchmark/Services/DeviceServiceBenchmark.cs
benchmark/Wangkanai.Detection.Benchmark.csproj

Restructure project for better expand ability

Refactor Benchmark project structure

---

src/Wangkanai.Detection.csproj

Testing the concept of strong naming the asssembly.

Add Strong Naming #364

---

appveyor.yml

Following the instruction from SignPath Documentation.
https://about.signpath.io/documentation/build-system-integration#appveyor

Update AppVeyor with SignPath

---

appveyor.yml

remove something that never used.

remove deploy myget from master

---

appveyor.yml

using the release signing of SignPath

change sign path to release signing

---

sample/ResponsivePage/Startup.cs
test/Services/DeviceServiceTest.cs

Refer #387 add unit testing for iPad Mini

add ipad mini testing

---

sample/ResponsivePage/Startup.cs
src/DependencyInjection/DetectionCollectionExtensions.cs
src/DependencyInjection/Options/DetectionOptions.cs

Reference to issue #387 and #390

Validate that the responsive options is working as planned

---

.editorconfig

**Add file headers to existing files, projects, and solutions with EditorConfig**: You will first need to add the file_header_template rule to your EditorConfig file. You will then need to set the value to equal the header text you would like applied. Add file header rule
Next, place your cursor on the first line of any C# or Visual Basic file and type (Ctrl+.) to trigger the Quick Actions and Refactorings menu. Select Add file banner. If you would like to apply the file header to all files of an existing project or solution, select Project or Solution under the Fix all occurrences in: option. Add file header
Reference: https://docs.microsoft.com/en-us/visualstudio/releases/2019/release-notes#16.6.0

Add header rule in editorconfig

---

src/Services/EngineService.cs
src/Services/Interfaces/IEngineService.cs
src/Services/Interfaces/IPlatformService.cs

#359 Thank you @ekersale for help remaining me

Add Version to IPlatformService

---

src/Services/UserAgentService.cs
test/Services/UserAgentServiceTest.cs

#442 null check should be or not and
Therefore, temporary unit test null checking is commented out. will find a better solution in later date.

fixed from and to or is null check

---

src/Builder/ApplicationBuilderExtensions.cs
src/DependencyInjection/DetectionBuilder.cs
src/DependencyInjection/DetectionCollectionExtensions.cs
src/DependencyInjection/DetectionCoreBuilderExtensions.cs
src/DependencyInjection/ResponsiveBuilderExtensions.cs
src/Options/CrawlerOptions.cs
src/Options/DetectionOptions.cs
src/Options/ResponsiveOptions.cs
src/Services/CrawlerService.cs
src/Services/ResponsiveService.cs
test/Builder/ApplicationBuilderExtensionsTest.cs
test/DependencyInjection/DetectionCoreBuilderExtensionsTest.cs
test/DependencyInjection/ResponsiveBuilderExtensionsTest.cs
test/Mocks/MockServer.cs
test/Mocks/MockService.cs
test/Services/CrawlerServiceTest.cs
test/Services/ResponsiveServiceTest.cs

A lot of breaking changes in this alpha release 😄

morning refactor with the mind is clear

---

src/Hosting/PageRouteModelConvention.cs
src/Services/Interfaces/IUserAgentService.cs
src/Services/UserAgentService.cs

Fixed Null exception in UserAgentService

---

src/Extensions/UserAgentExtensions.cs
src/Extensions/VersionExtensions.cs
src/Services/BrowserService.cs
test/Builder/ApplicationBuilderExtensionsTest.cs
test/DependencyInjection/DetectionCoreBuilderExtensionsTest.cs
test/DependencyInjection/ResponsiveBuilderExtensionsTest.cs
test/Extensions/VersionExtensionsTest.cs
test/Services/BrowserServiceTest.cs

Fixed safari version parse bug

---

Directory.Build.props
src/Services/PlatformService.cs
test/Hosting/ResponsiveMiddlewareTest.cs
test/Mocks/MockServer.cs
test/Services/PlatformServiceTest.cs

#501 Add engine webkit to generic list

Fixed bug iPhone as Mac

---

Markdown/Directory.Build.props
Multitenant/Directory.Build.props
Responsive/Directory.Build.props
Runtime/Directory.Build.props
Runtime/src/Wangkanai.Runtime.csproj
Universal/Directory.Build.props
Universal/src/DependencyInjection/UniversalApplicationExtensions.cs
Universal/src/Wangkanai.Universal.csproj
Wangkanai.sln
Webmaster/Directory.Build.props
Webserver/Directory.Build.props
sign-hosting.ps1

Separate the dependency to only what is matter to the code on hand with a modular design

Hosting project dependency

---

Hosting/src/Abstractions/IMarkerService.cs
Hosting/src/DependencyInjection/CoreBuilderExtensions.cs
Hosting/src/Services/MarkerService.cs
Hosting/test/Extensions/ApplicationBuilderExtensionsTests.cs
Hosting/test/Usings.cs
Hosting/test/Wangkanai.Hosting.Test.csproj
Wangkanai.sln

layout the unit testing for Hosting module.

Add Hosting CI Testing

---

Tabler/Directory.Build.props
Tabler/demo/Client/package.json
Tabler/tests/Wangkanai.Tabler.Tests.csproj

Tablar Update

---

Analytics/Directory.Build.props
Blazor/Directory.Build.props
Detection/Directory.Build.props
Responsive/Directory.Build.props
Runtime/Directory.Build.props
Runtime/src/Domain/AbstractTypeFactory.cs
Runtime/src/Extensions/EnumerableExtensions.cs
Runtime/src/Extensions/FormattingExtensions.cs
Runtime/src/Extensions/IQueryableExtensions.cs
Runtime/src/Extensions/KeyValuePairExtensions.cs
Runtime/src/Extensions/StringExtensions.cs
Runtime/src/Wangkanai.Runtime.csproj
Tabler/Directory.Build.props
Universal/Directory.Build.props
Validation/Directory.Build.props
Webmaster/Directory.Build.props
Webserver/Directory.Build.props

- Add IQueryable Method Extensions
- Add Abstract Type Factory

Runtime helper extensions

---

README.md

Update Tabler with the new CSS fixes

---

Federation/README.md

Reference to issue #606 and discussion #605

Update Federation README.md

---

System/src/Collections/ComparisonComparer.cs
System/src/Collections/DictionaryByType.cs
System/src/Collections/LinkedComparer.cs
System/src/Collections/ProjectionComparer.cs
System/src/Collections/ProjectionEqualityComparer.cs
System/tests/Collections/DictionaryByTypeTests.cs
System/tests/Collections/NameAndNumber.cs
System/tests/Collections/ProjectionComparerTests.cs
System/tests/Collections/ProjectionEqualityComparerTests.cs
System/tests/xunit.runner.json

Add collection extensions to system

---

Analytics/Directory.Build.props
Blazor/Directory.Build.props
Detection/Directory.Build.props
Domain/Directory.Build.props
EntityFramework/Directory.Build.props
Extensions/CommandLine/Directory.Build.props
Extensions/Directory.Build.props
Extensions/FileProviders/Directory.Build.props
Extensions/Html/Directory.Build.props
Federation/Directory.Build.props
Graph/Directory.Build.props
Hosting/Directory.Build.props
Markdown/Directory.Build.props
Multitenant/Directory.Build.props
Responsive/Directory.Build.props
Security/Directory.Build.props
SendGrid/Directory.Build.props
Solver/Directory.Build.props
Solver/src/Wangkanai.Solver.csproj
System/Directory.Build.props
Tabler/Directory.Build.props
Tools/Directory.Build.props
Tools/MSBuild/Directory.Build.props
Tools/SignCode/Directory.Build.props
Universal/Directory.Build.props
Validation/Directory.Build.props
Watcher/Directory.Build.props
Watcher/src/Wangkanai.Watcher.csproj
Webmaster/Directory.Build.props
Webserver/Directory.Build.props

All subproject Directory.Build.props import the solution Directory.Build.props

---

Multitenant/src/DependencyInjection/MultiTenantApplicationExtensions.cs
Responsive/src/DependencyInjection/ResponsiveCoreBuilderExtensions.cs
Responsive/src/Services/ResponsiveService.cs
System/Directory.Build.props
System/src/Check.cs
System/src/Collections/RandomAccessQueue.cs
System/src/Cryptography/Adler32.cs
System/src/Math.cs
System/tests/CheckTests.cs
System/tests/Collections/RandomAccessQueueTests.cs

I would like the core to be every versatile as much as possible.

Enhance the core system library

---

System/src/Collections/RandomAccessQueue.cs
System/src/Collections/Range.cs
System/src/Collections/RangeIterator.cs
System/src/Collections/ReverseComparer.cs
System/src/Extensions/ComparerExtensions.cs
System/tests/Collections/RangeIteratorTests.cs
System/tests/Collections/RangeTests.cs
System/tests/Collections/ReverseComparerTests.cs
System/tests/Extensions/ComparerExtensionsTests.cs

- RangeIterator
- ReverseComparer
- ComparerExtensions

Range collection utility and ReverseComparer

---

.github/design_note.md
Wangkanai.sln

I need to build out a habit of planning what to do in advance and keep tasks organized with well documentation

add design note template to github

---

Federation/src/BackendForFrontend/Constants.cs
Federation/src/BackendForFrontend/Wangkanai.Federation.BackendForFrontend.csproj
Wangkanai.sln

Federation Backend for Frontend

---

Blazor/src/Web/package.json
Federation/src/Federation/Wangkanai.Federation.csproj
Graph/src/Wangkanai.Graph.csproj
Tabler/src/Web/package.json

- update npm package tabler
- update npm package blazor

update tabler npm package

---

System/Directory.Build.props
System/src/Math.cs

- short divider 
- int divider
- long divider
- float divider
- double divider
- decimal divider

add divider to math

---

Federation/tests/Federation/Services/MarkerServiceTests.cs
Federation/tests/Federation/Validations/ValidationRequestTests.cs
Federation/tests/Federation/Wangkanai.Federation.Tests.csproj

Add xunit unit tests project foundation
- Validations
- Services
- Hosting
- Endpoints
- Extensions
- Responses

Federation unit tests framework

---

Analytics/Directory.Build.props
Blazor/Directory.Build.props
Detection/Directory.Build.props
Domain/Directory.Build.props
EntityFramework/Directory.Build.props
Extensions/CommandLine/Directory.Build.props
Extensions/FileProviders/Directory.Build.props
Extensions/Html/Directory.Build.props
Federation/Directory.Build.props
Graph/Directory.Build.props
Hosting/Directory.Build.props
Identity/Directory.Build.props
Markdown/Directory.Build.props
Responsive/Directory.Build.props
Security/Directory.Build.props
SendGrid/Directory.Build.props
Solver/Directory.Build.props
System/Directory.Build.props
Tabler/Directory.Build.props
Tools/SignCode/Directory.Build.props
Universal/Directory.Build.props
Validation/Directory.Build.props
Webmaster/Directory.Build.props
Webserver/Directory.Build.props

publish new nuget version

---

Web/src/Properties/launchSettings.json

Lets start make our library to expose to more public attention to help gain project momentum.

start working on the wangkanai web

---

Extensions/CommandLine/Directory.Build.props
Extensions/Directory.Build.props
Extensions/FileProviders/Directory.Build.props
Extensions/Html/Directory.Build.props
Extensions/Internal/Directory.Build.props
Federation/Directory.Build.props
Markdown/Directory.Build.props
Security/Directory.Build.props
Tools/Directory.Build.props
Tools/MSBuild/Directory.Build.props
Tools/SignCode/Directory.Build.props
Wangkanai.sln
sign.ps1

I have created a PowerShell script to help me automate the NuGet signing and publishing in order of library dependencies amount each other.

PowerShell to sign all packages in order of dependency

---

Markdown/src/DependencyInjection/MarkdownEndpointRouteBuilderExtensions.cs
Markdown/src/Infrastructure/DynamicMarkdownEndpointDataSelectorCache.cs
Markdown/src/Infrastructure/DynamicMarkdownEndpointSelector.cs
Markdown/src/Infrastructure/DynamicMarkdownMetadata.cs
Markdown/src/Infrastructure/DynamicMarkdownRouteValueTransformerMetadata.cs
Markdown/src/Infrastructure/MarkdownActionEndpointDataSource.cs
Markdown/src/Infrastructure/MarkdownActionEndpointDataSourceFactory.cs
Markdown/src/Infrastructure/MarkdownActionEndpointDataSourceIdProvider.cs
Markdown/src/Infrastructure/MarkdownEndpointDataSourceIdMetadata.cs
Markdown/src/Models/IMarkdownConvention.cs
Markdown/src/Models/MarkdownConventionCollection.cs
Markdown/src/Wangkanai.Markdown.csproj
Mvc/src/Controllers/ControllerActionDescriptor.cs
Mvc/src/Controllers/ControllerBinderDelegate.cs
Mvc/src/Infrastructure/ActionSelectionTable.cs
Mvc/src/Infrastructure/ControllerEndpointFilterInvocationContext.cs
Mvc/src/Infrastructure/OrderedEndpointsSequenceProvider.cs
Mvc/src/Routing/ActionEndpointDataSourceBase.cs
Mvc/src/Routing/DataSourceDependentCache.cs
System/src/Check.cs
System/src/Collections/StringArrayComparer.cs
System/src/Properties/AssemblyInfo.cs
Web/src/Program.cs

- Further, investigate the ability to layout the framework
- I have done an extensive major overhaul of the namespace in the whole repo, so their shall be a lot of breaking changes to come soon.

Mvc framework internal component bring to wangkanai

---

Analytics/Directory.Build.props
Blazor/Directory.Build.props
Detection/Directory.Build.props
Domain/Directory.Build.props
EntityFramework/Directory.Build.props
Extensions/Directory.Build.props
Federation/Directory.Build.props
Graph/Directory.Build.props
Hosting/Directory.Build.props
Identity/Directory.Build.props
Markdown/Directory.Build.props
Mvc/Directory.Build.props
Responsive/Directory.Build.props
Security/Directory.Build.props
Solver/Directory.Build.props
System/Directory.Build.props
Tabler/Directory.Build.props
Tools/Directory.Build.props
Universal/Directory.Build.props
Validation/Directory.Build.props
Watcher/Directory.Build.props
Webmaster/Directory.Build.props
Webserver/Directory.Build.props
sign.ps1

Release the new updates for all the library depending on System.

nuget publish new system updates

---

System/src/Check.cs
System/src/Resources/ObsoleteResources.cs
System/tests/CheckTests.cs
System/tests/CustomNullException.cs

This is make sure that check has everything covered for null checking. I do know that future .NET 7 onwards will have nullable enforce in the framework, but until then this my preferred way of coding.

[System] Check all possible null and re-organize methods

---

System/benchmark/CheckBenchmark.cs
System/benchmark/Program.cs
System/benchmark/Wangkanai.System.Benchmark.csproj
System/src/Check.cs
System/src/Exceptions/ArgumentNegativeException.cs
System/src/Exceptions/ArgumentPositiveException.cs
System/src/Resources/SystemResources.cs
System/tests/StaticRandomTests.cs
System/tests/Wangkanai.System.Tests.csproj

Lets get this function into the base system.

[System] Check if positive and negative

---

Web/src/package.json

Upgrade web npm bootstrap 5.3.0 public release

upgrade npm bootstrap 5.3.0

---

Blazor/README.md
Blazor/demo/Client/Wangkanai.Blazor.Demo.Client.csproj
Blazor/demo/Client/wwwroot/index.html

Welcome to `Wangkanai Blazor`! This project hosts a collection of carefully crafted components designed to breathe life into your Blazor applications. Our components follow common interaction patterns and adhere to the highest standards of semantic specifications, offering you reliable building blocks for your web UI.

[Blazor] Introduction and project clean up

---

Detection/samples/mvc/DetectionMvc.csproj
Wangkanai.sln
Wangkanai.sln.DotSettings

Streamline the code to be more efficient

[Detection] Migrate sample from .net6 to .net7

---

Federation/src/EntityFramework/Extensions/ModelBuilderExtensions.cs
Federation/src/EntityFramework/Options/ConfigurationStoreOption.cs
Federation/src/EntityFramework/Options/TableConfiguration.cs

```csharp
private static EntityTypeBuilder<TEntity> ToTable<TEntity>(this EntityTypeBuilder<TEntity> builder, TableConfiguration config)
where TEntity : class
=> config.Schema.IsNullOrWhiteSpace()
? builder.ToTable(config.Name)
: builder.ToTable(config.Name, config.Schema);
```

[Federation] fixed the recurring method

---

Federation/hosts/AspNetIdentity/Host.AspNetIdentity.csproj
Federation/hosts/AspNetIdentity/package.json
Federation/hosts/EntityFramework/Host.EntityFramework.csproj
Federation/hosts/EntityFramework/package.json
Federation/hosts/Main/Host.Main.csproj
Federation/hosts/Main/package.json

[Federation] Remove hardcode external dependency

---

Analytics/benchmark/AnalyticsBenchmark.cs
Analytics/benchmark/Program.cs
Blazor/src/Components/RenderTree/ArrayRange.cs
Blazor/src/Components/RenderTree/RenderTreeDiffBuilder.cs
Blazor/src/Components/Rendering/RenderTreeBuilder.cs
Detection/tests/Wangkanai.Detection.Tests.csproj
Extensions/CommandLine/src/CommandLineApplication.cs
Extensions/CommandLine/src/Properties/AssemblyInfo.cs
Extensions/Internal/src/ObjectMethodExecutorFSharpSupport.cs
System/src/Check.cs
Wangkanai.sln

clean up the code smell in the repository

fixing general bugs in the code base

---

Analytics/benchmark/Wangkanai.Analytics.Benchmark.csproj
Blazor/benchmark/Wangkanai.Blazor.Benchmark.csproj
Detection/benchmark/DetectionBenchmark.cs
Detection/benchmark/Program.cs
Detection/benchmark/Wangkanai.Detection.Benchmark.csproj
Domain/benchmark/Wangkanai.Domain.Benchmark.csproj

Fixed code unit test coverage

---

Web/src/tsconfig.json

[Web] fixed tsconfig.json include bug

---

Domain/tests/Wangkanai.Domain.Tests.csproj

See what can be refactor and clean up

[Domain] Update nuget packages

---

EntityFramework/tests/Wangkanai.EntityFramework.Tests.csproj

update the unit test nuget packages

[EFCore] Update nuget packages

---

.gitignore
Federation/tests/Federation/Wangkanai.Federation.Tests.csproj
Markdown/samples/Markdown/Markdown.csproj
Wangkanai.sln
Web/src/Wangkanai.Web.Server.csproj
dotnet-analysis.ps1
sonar-scanner.properties

Add SonarScanner Cloud configuration

[Federation] Update nuget package

---

Extensions/CommandLine/tests/Wangkanai.Extensions.CommandLine.Tests.csproj
Extensions/FileProviders/tests/Wangkanai.Extensions.FileProviders.Tests.csproj
Extensions/Html/tests/Wangkanai.Extensions.Html.Tests.csproj
Extensions/Internal/tests/Wangkanai.Extensions.Internal.Test.csproj

update the remain nuget packages

[Extensions] Update nuget packages

---

Identity/tests/Wangkanai.Identity.Tests.csproj

[Identity] Update nuget packages

---

Markdown/tests/Wangkanai.Markdown.Test.csproj

update unit test nuget packages

[Markdown] Update nuget packages

---

Markdown/src/Infrastructure/DynamicMarkdownEndpointSelector.cs
Mvc/src/Infrastructure/ActionSelectionTable.cs
Mvc/src/Routing/DataSourceDependentCache.cs
Mvc/tests/Wangkanai.Mvc.Test.csproj

- Update unit test nuget packages

[Mvc] The 'Count' of 'ICollection' always evaluates as 'True' regardless

---

Security/tests/Security/Wangkanai.Security.Tests.csproj

[Security] Update nuget package

---

.gitignore
Universal/benchmark/Program.cs
Universal/benchmark/TrackerServiceBenchmark.cs
Universal/tests/Wangkanai.Universal.Test.csproj

[University] Update nuget packages

---

Wangkanai.sln
sonar-project.properties

sonar-project.properties for the azure pipeline sonar prepare configuration of standalone scanner.

Store the sonar configuration in the source code

---

Federation/src/Federation/Endpoints/DiscoveryEndpoint.cs
Federation/src/Federation/Hosting/EndpointRouter.cs

- https://sonarcloud.io/organizations/wangkanai/rules?open=csharpsquid%3AS2234&rule_key=csharpsquid%3AS2234

[Federation] Parameters should be passed in the correct order

---

Detection/src/Constants.cs
Detection/src/Extensions/VersionExtensions.cs
Detection/src/Services/PlatformService.cs
Detection/src/Wangkanai.Detection.csproj

- https://sonarcloud.io/organizations/wangkanai/rules?open=csharpsquid%3AS6444&rule_key=csharpsquid%3AS6444

[Detection] Regex with timeout

---

System/src/Constants.cs
System/src/Cryptography/Hash.cs
System/src/Extensions/StringExtensions.cs

- https://sonarcloud.io/organizations/wangkanai/rules?open=csharpsquid%3AS6444&rule_key=csharpsquid%3AS6444

[System] Regex require timeout

---

Universal/src/Models/ConfigOption.cs
Universal/src/Models/Set.cs

There is no way for us to access the private constructor from a public class

[Universal] Make the instance constructor to public

---

.gitignore
Directory.Build.props

Consolidate and unify the repository directory structure to be more organize and maintenance able.

Refactor solution directory structure

---

Analytics/Directory.Build.props
Blazor/Directory.Build.props
Detection/Directory.Build.props
Domain/Directory.Build.props
EntityFramework/Directory.Build.props
Extensions/Directory.Build.props
Federation/Directory.Build.props
Graph/Directory.Build.props
Hosting/Directory.Build.props
Identity/Directory.Build.props
IdentityAdmin/Directory.Build.props
Markdown/Directory.Build.props
Mvc/Directory.Build.props
Responsive/Directory.Build.props
Security/Directory.Build.props
Solver/Directory.Build.props
System/Directory.Build.props
System/src/Attributes/DeprecateAttribute.cs
System/tests/Collections/ComparisonComparerTests.cs
Tabler/Directory.Build.props
Tools/Directory.Build.props
Universal/Directory.Build.props
Validation/Directory.Build.props
Watcher/Directory.Build.props
Webmaster/Directory.Build.props
Webserver/Directory.Build.props
version-up.ps1

This is depreciated .NET Standard 2.1 from the base components for newly add features of the new C# 11 fully

Publish nuget packages for platform migration

---

System/Directory.Build.props
System/src/Check.cs
System/src/Decorator.cs
System/src/Wangkanai.System.csproj
System/tests/CheckTests.cs
System/tests/DecoratorTests.cs
System/tests/MathTests.cs
Validation/src/Wangkanai.Validation.csproj

- Code Coverage is only target framework level also

[System] Refactor and add unit test for more code coverage

---

System/src/Check.cs
System/src/Decorator.cs
Validation/tests/xunit.runner.json

All 'ThrowIfNull' method overloads should be adjacent
Reference: https://sonarcloud.io/project/issues?open=AYiOyH928PTBoU7GMNrN&id=wangkanai_wangkanai

[System] reorganize overall into type

---

.gitattributes

This repo is primary written C#, but GitHub seem to give weight that this repo is more than 50% HTML.

[Git] Don't identity language HTML

---

System/README.md

This is to make people better understand the propose of developing this library and encourage them participate more to improve the functionality of the project.

[System] Rewrite `System` project readme introduction

---

System/src/Extensions/StringExtensions.cs
System/tests/Extensions/Strings/StringDirectionSubstringTests.cs

[System] String extensions substring unit tests

---

System/src/Extensions/StringExtensions.cs
System/tests/Extensions/Strings/StringRemoveFix.cs

- All more native capabilities ti string extensions for removing pro & post fixes
- Add unit tests to make sure that the function is working as expected

[System] add overload string extensions remove pre & post fixes 

---

System/src/Check.cs
System/src/Exceptions/ArgumentEmptyException.cs
System/src/Exceptions/ArgumentNullOrEmptyException.cs
System/src/Exceptions/ArgumentNullOrWhitespaceException.cs
System/src/Exceptions/ArgumentWhitespaceException.cs
System/src/Extensions/StringExtensions.cs
System/src/Resources/SystemResources.cs
System/tests/Checks/CheckCompareTests.cs
System/tests/Checks/CheckStringTests.cs
System/tests/Extensions/Strings/StringEnumTests.cs
System/tests/Extensions/Strings/StringNullTests.cs
System/tests/Extensions/Strings/StringRemoveFix.cs

This function looks so simple, but it's so powerful even beyond my imagination. Writing the unit tests for this function help me a lot.

[System] string extensions convert to enum

---

.gitattributes

repo language parser incorrectly into HTML

---

System/src/Extensions/StringExtensions.cs
System/tests/Extensions/Strings/StringTruncateTests.cs

- string truncate with max length
- string truncate with max length by adding trailing postfix

[System] string extensions truncate

---

System/src/Extensions/StringExtensions.cs
System/tests/Extensions/Strings/StringSubstring.cs
System/tests/Extensions/Strings/StringTrimTests.cs

- refactor the string extensions for substring
- add unit tests

[System] string extensions for substring safely

---

System/src/Extensions/StringExtensions.cs
System/tests/Extensions/Strings/StringTitleCaseTests.cs
dotnet-sonar.ps1
global.json

- refactor the function
- add unit tests

[System] string extensions to title case

---

README.md

Update README.md with Azure kanban board status

---

Federation/src/Federation/Responses/Models/AuthorizeResponse.cs
System/src/Extensions/StringExtensions.cs
System/tests/Extensions/Strings/StringEscapeTests.cs
System/tests/Extensions/Strings/StringSubstringTests.cs

- Refactor the functions into more reuse able components
- Add unit tests to safe control code quality

[System] string extensions escape unit tests

---

Blazor/src/Components/RenderTree/ArrayRange.cs
Extensions/CommandLine/src/CommandLineApplication.cs
System/src/Extensions/StringExtensions.cs
System/tests/Extensions/Strings/StringEscapeTests.cs

- refactor the function to be more performance
- add unit tests
[AB#766](https://dev.azure.com/wangkanai/e03e9c5f-ef72-4783-b288-5a5383d5511f/_workitems/edit/766)

[System] string extensions escape search

---

System/src/Extensions/StringExtensions.cs
System/tests/Extensions/Strings/StringSelectorTests.cs

[AB#765](https://dev.azure.com/wangkanai/e03e9c5f-ef72-4783-b288-5a5383d5511f/_workitems/edit/765) Task

[System] string escape selector with double backslash

---

System/tests/Extensions/Strings/StringSlugTests.cs

- refactor the method extensions
- add unit tests to sage guard the logic specification

[System] string extensions generate slug

---

System/src/Extensions/StringExtensions.cs
System/tests/Extensions/Strings/StringAccentTests.cs
System/tests/Extensions/Strings/StringEnumTests.cs
System/tests/Extensions/Strings/StringEscapeTests.cs
System/tests/Extensions/Strings/StringRemoveFix.cs
System/tests/Extensions/Strings/StringSelectorTests.cs
System/tests/Extensions/Strings/StringSlugTests.cs
System/tests/Extensions/Strings/StringSubstringTests.cs
System/tests/Extensions/Strings/StringTitleCaseTests.cs
System/tests/Extensions/Strings/StringTrimTests.cs
System/tests/Extensions/Strings/StringTruncateTests.cs

- refactoring the string extensions
- reduce duplicated functions that produce the same results [AB#775](https://dev.azure.com/wangkanai/e03e9c5f-ef72-4783-b288-5a5383d5511f/_workitems/edit/775)

[System] string extensions refactoring

---

System/src/Check.cs
System/tests/Checks/CheckEmptyTests.cs
System/tests/CustomEmptyException.cs
System/tests/CustomNullException.cs

- add check if the list is empty
- add unit tests

[System] check if IEnumerable is empty

---

System/src/Extensions/CollectionExtension.cs
System/src/Extensions/ObservableCollectionExtensions.cs
System/tests/Extensions/CollectionExtensionsTests.cs

- optimize the performance of the code
- add unit tests to validate the design logic

[System] Collection extensions refactor and unit tests

---

System/src/Extensions/TypeExtensions.cs
System/tests/Extensions/TypeExtensionsTests.cs

- make sure that the type extensions are what that was designed to be
- add unit tests to safeguard the code for bug

[System] Type extensions refactoring and unit tests

---

Analytics/Directory.Build.props
Blazor/Directory.Build.props
Detection/Directory.Build.props
Domain/Directory.Build.props
EntityFramework/Directory.Build.props
Extensions/Directory.Build.props
Federation/Directory.Build.props
Hosting/Directory.Build.props
Identity/Directory.Build.props
Markdown/Directory.Build.props
Mvc/Directory.Build.props
Responsive/Directory.Build.props
Security/Directory.Build.props
Solver/Directory.Build.props
Tabler/Directory.Build.props
Tools/Directory.Build.props
Validation/Directory.Build.props
Watcher/Directory.Build.props
Web/Directory.Build.props
Webmaster/Directory.Build.props
Webserver/Directory.Build.props

This is start every to be develop upon .NET 7 and further in the future for .NET 8

all upgrade projects version in repository

---

Blazor/Directory.Build.props
Blazor/src/Components/Routing/QueryParameterValueSupplier.cs

Rewrite the project readme and package description

[Blazor] project introduction for better discovery

---

Analytics/Directory.Build.props
Analytics/INSTALL.md
Analytics/README.md
Wangkanai.sln

- split readme for description only
- installation has its own markdown
- rewrite nuget package description

[Analytics] Rewrite project introduction

---

Detection/Directory.Build.props

- increase search able nuget package

[Detection] Rewrite detection introduction

---

Federation/Directory.Build.props
Federation/README.md

- Rewrite the project readme file
- Rewrite nuget package description

[Federation] Rewrite introduction for better discovery

---

EntityFramework/Directory.Build.props
EntityFramework/README.md

[EntityFramework] Rewrite EntityFramework introduction

---

Markdown/Directory.Build.props
Markdown/INSTALL.md
Markdown/README.md
Wangkanai.sln

[Markdown] Rewrite markdown introduction

---

Security/Directory.Build.props
Security/README.md

[Security] Rewrite security introduction

---

Domain/README.md
Wangkanai.sln
Webmaster/Directory.Build.props
Webmaster/INSTALL.md
Webmaster/README.md

[Webmaster] Rewrite webmaster introduction

---

Solver/Directory.Build.props
Solver/README.md
System/README.md

[Solver] Rewrite solver introduction

---

Tabler/Directory.Build.props
Tabler/README.md

[Tabler] Rewrite tabler introduction

---

Webserver/Directory.Build.props
Webserver/README.md

[Webserver] Rewrite webserver introduction

---

Validation/Directory.Build.props
Validation/README.md

[Validation] Rewrite validation introduction

---

Responsive/src/DependencyInjection/ResponsiveBuilder.cs
Responsive/src/DependencyInjection/ResponsiveCollectionExtensions.cs
Testing/src/AssertionOptions.cs
Testing/src/Builders/AssertionBuilder.cs
Testing/src/Builders/IAssertionBuilder.cs
Testing/src/DependencyInjection/AssertionCollectionExtensions.cs
Testing/src/Properties/AssemblyInfo.cs
Testing/src/Services/AssertionMarkerService.cs
Testing/src/Services/AssertionService.cs
Testing/src/Services/IAssertionService.cs
Testing/src/Services/IScopedService.cs
Testing/src/Services/ISingletonService.cs
Testing/src/Services/ITransientService.cs
Testing/src/Services/ScopedService.cs
Testing/src/Services/SingletonService.cs
Testing/src/Services/TransientService.cs
Testing/src/Wangkanai.Testing.csproj
Testing/tests/Extensions/AssertionHelperExtensionsTests.cs

- add unit tests code coverage
- refactor namespaces

[Testing] Add unit tests code coverage

---

Directory.Build.props
SonarQube.Analysis.xml

- fixed the code coverage not working issue

[Sonar] Exclude tests from source

---

Directory.Build.targets
Federation/src/EntityFramework/Wangkanai.Federation.EntityFramework.csproj

- This is simple fixed when review it again from the foundation

[Federation] Fixed central ef core package reference

---

System/Directory.Build.props

A better nuget package description is required.

[System] rewrite the nuget package description

---

Cryptography/Directory.Build.props
Cryptography/README.md
Cryptography/src/Adler32.cs
Cryptography/tests/Adler32Tests.cs

* [Rolling Hash - Wikipedia](https://en.wikipedia.org/wiki/Rolling_hash)
* [Rolling Hash – Data Structures and Algorithms](https://www.geeksforgeeks.org/introduction-to-rolling-hash-data-structures-and-algorithms/)

[Cryptography] Investigate furthere into hash agroritm

---

System/src/Extensions/StringExtensions.cs
System/tests/Extensions/Strings/StringSplitTests.cs

How to make pull requests into features trigger a continuous build?

[System] add string extensions unit tests

---

Blazor/src/Components/Rendering/RendererSynchronizationContext.cs
Directory.Build.targets
Extensions/CommandLine/tests/Wangkanai.Extensions.CommandLine.Tests.csproj
Extensions/Html/src/Wangkanai.Extensions.Html.csproj
Extensions/Internal/src/CoercedAwaitableInfo.cs
Federation/tests/Domain/Validations/GrantTypeValidationTests.cs
Markdown/src/MarkdownViewEngine.cs
Mvc/src/Infrastructure/ActionSelectionTable.cs
Wangkanai.sln
Webserver/src/Extensions/HttpResponseExtensions.cs
global.json

- Optimizing identifiable code high warming

Refactor code optimization with Qodana

---

System/Directory.Build.props
System/src/Extensions/EnumExtensions.cs
System/src/Extensions/EnumValues.cs
System/src/Extensions/StringExtensions.cs
System/src/Wangkanai.System.csproj
Wangkanai.argr

- System should be clear from any compiler warnings

[System] refactor and fix no warning

---

System/Directory.Build.props
System/src/Exceptions/ArgumentEmptyException.cs
System/src/Exceptions/ArgumentEqualException.cs
System/src/Exceptions/ArgumentLessThanException.cs
System/src/Exceptions/ArgumentMoreThanException.cs
System/src/Exceptions/ArgumentNegativeException.cs
System/src/Exceptions/ArgumentNotEqualException.cs
System/src/Exceptions/ArgumentNullOrEmptyException.cs
System/src/Exceptions/ArgumentNullOrWhitespaceException.cs
System/src/Exceptions/ArgumentPositiveException.cs
System/src/Exceptions/ArgumentWhitespaceException.cs
System/src/Exceptions/ArgumentZeroException.cs
System/src/Usings.cs

The ISerializable interface is the mechanism to control the type serialization process. If not implemented correctly this could result in an invalid serialization and hard-to-detect bugs.
https://sonarcloud.io/project/issues?open=AYjXVJEHTmPOlqSrGsa-&id=wangkanai_wangkanai

[System] Sealed the custom argument exception

---

Directory.Build.props
System/benchmark/CheckNumericBenchmark.cs
System/benchmark/Program.cs
System/benchmark/StringSpanVsSubstringBenchmark.cs
System/benchmark/Wangkanai.System.Benchmark.csproj
System/src/Extensions/StringExtensions.cs
System/src/Wangkanai.System.csproj
global.json

- Use AsSpan vs Substring
- Fixed benchmark not running
Some thing is not right now??

[System] Enhance performance of string title case

---

System/src/Check.cs
System/src/Properties/AssemblyInfo.cs
System/tests/Checks/CheckCompareTests.cs
System/tests/Checks/CheckEmptyListTests.cs
System/tests/Checks/CheckEmptyStringTests.cs
System/tests/Checks/CheckNullTests.cs
System/tests/Checks/CheckNumericTests.cs
System/tests/Checks/CheckStringTests.cs
System/tests/Checks/CreateExceptionInstanceTests.cs

- Check throw if null adjacent
- Rearrange throw with except message

[System] Fixed code smell for better efficiency

---

System/Directory.Build.props
System/src/Collections/DictionaryByType.cs
System/src/Collections/RandomAccessQueue.cs
System/src/Collections/RangeIterator.cs
System/src/Domain/AbstractTypeFactory.cs
System/src/Domain/GenericTypeInfo.cs
System/tests/Domain/AbstractTypeFactoryTests.cs
System/tests/Domain/GenericTypeInfoTests.cs
Wangkanai.argr
sonar-begin.ps1
sonar-prep.ps1

- [Refactor dictionary by type](https://github.com/wangkanai/wangkanai/pull/885/commits/9b9e10c4fcd09f939c97e32e3471274e954c2096)
- [Refactor abstract type factory](https://github.com/wangkanai/wangkanai/pull/885/commits/7f265343d01081e6be74446d33cfcffe0b9f2613)
- [Refactor random access queue](https://github.com/wangkanai/wangkanai/pull/885/commits/b97023cd014d8ff5c613b36dc861cb5702b1db91)
- [Refactor range iterator](https://github.com/wangkanai/wangkanai/pull/885/commits/93a7d3eb667366e4af377c99f6ec0648b4ec1391)
- [Refactor generic type info](https://github.com/wangkanai/wangkanai/pull/885/commits/5a78e69fbcaad39e7bc45186d4072dc9ce99dd98)

[System] improvement performance code in collection

---

System/src/Domain/AbstractTypeFactory.cs
System/src/Domain/GenericTypeInfo.cs
System/src/Extensions/StringExtensions.cs
System/src/Extensions/TreeExtensions.cs
System/src/Extensions/TypeExtensions.cs

- https://sonarcloud.io/project/issues?open=AYiOyH9M8PTBoU7GMNrH&id=wangkanai_wangkanai
- [Use 'StringBuilder.Append(char)' instead of 'StringBuilder.Append(string)' when the input is a constant unit string](https://sonarcloud.io/project/issues?open=AYiQOxPBGLfIxx_yfDhH&id=wangkanai_wangkanai)

[System] Abstract type factory refactoring

---

Directory.Build.targets
Extensions/Html/src/Wangkanai.Extensions.Html.csproj
Federation/src/Federation/Wangkanai.Federation.csproj
System/Directory.Build.props
sonar-begin.ps1
sonar-prep.ps1

- update latest nuget packages

Upgrade nuget packages

---

Blazor/Directory.Build.props
Blazor/src/Core/Wangkanai.Blazor.csproj
Tabler/Directory.Build.props
Validation/Directory.Build.props
Validation/src/RequireFalseAttribute.cs
Validation/src/RequireNonAlphanumericAttribute.cs

- publish blazor nuget package
- fixed blazor nuget Components private assets not include in publish package

[Tabler] Refactor and project cleanup

---

Extensions/CommandLine/src/AnsiConsole.cs
Extensions/CommandLine/src/CommandArgument.cs
Extensions/CommandLine/src/CommandLineApplication.cs
Extensions/CommandLine/tests/CommandArgumentTests.cs
Extensions/CommandLine/tests/CommandLineApplicationTests.cs
Extensions/CommandLine/tests/CommandOptionTests.cs
Extensions/CommandLine/tests/Wangkanai.Extensions.CommandLine.Tests.csproj
Extensions/Directory.Build.props

- remove `<nowarn>`
- publish nuget 3.3

[Extensions] Clean code smell

---

Cryptography/src/HashRandom.cs
Extensions/CommandLine/src/CommandLineApplication.cs
Extensions/CommandLine/src/Extensions/ApplicationExtensions.cs
Extensions/CommandLine/src/Extensions/ExecuteExtensions.cs
Extensions/CommandLine/src/Extensions/HelpExtensions.cs
Extensions/CommandLine/src/Extensions/OptionExtensions.cs

https://sonarcloud.io/project/issues?open=AYsDUzpzt1PlUhiQzSA2&id=wangkanai_wangkanai

[Extensions] Commandline refactor and fix unit tests

---

Detection/src/TagHelpers/BrowserTagHelper.cs
Detection/tests/Mocks/MockService.cs
Detection/tests/TagHelpers/BrowserTagHelperTests.cs

[Detection] fixed has is always false

---

Detection/tests/Mocks/MockTagHelper.cs
Detection/tests/TagHelpers/BrowserTagHelperTests.cs
Detection/tests/Wangkanai.Detection.Tests.csproj

- detection tag helper unit tests

[Detection] Refactor unit tests

---

Directory.Build.props
Directory.Build.targets
Web/src/Wangkanai.Web.csproj

- directory.props
- directory.targets

[NuGet] Central package management

---

Directory.Build.targets
Extensions/Internal/src/Properties/AssemblyInfo.cs
Extensions/Internal/src/TypeNameHelper.cs
Extensions/Internal/tests/TypeNameHelperTests.cs
Extensions/Internal/tests/Wangkanai.Extensions.Internal.Tests.csproj

https://sonarcloud.io/project/issues?open=AYiOyIXB8PTBoU7GMNtJ&id=wangkanai_wangkanai

[Extensions] Reduce type name helper complexity

---

Detection/src/Extensions/IndexTree.cs
Detection/tests/Extensions/IndexTreeTests.cs

Reduce cognitive complexity of index tree

[Detection] Refector IndexTree for simplicity

---

Detection/src/Extensions/IndexTree.cs
Detection/src/Extensions/SearchExtensions.cs
Detection/src/Extensions/UserAgentExtensions.cs
Detection/src/Extensions/VersionExtensions.cs
System/src/Extensions/CollectionExtension.cs

- fixed keywords possible is null

[Detection] Resolve remaining code smell

---

Analytics/Directory.Build.props
Blazor/Directory.Build.props
Detection/Directory.Build.props
Domain/Directory.Build.props
EntityFramework/Directory.Build.props
Extensions/Directory.Build.props
Federation/Directory.Build.props
Hosting/Directory.Build.props
Identity/Directory.Build.props
Markdown/Directory.Build.props
Mvc/Directory.Build.props
Responsive/Directory.Build.props
Security/Directory.Build.props
Solver/Directory.Build.props
System/Directory.Build.props
Tabler/Directory.Build.props
Testing/Directory.Build.props
Tools/Directory.Build.props
Validation/Directory.Build.props
Webmaster/Directory.Build.props
Webserver/Directory.Build.props

- update the package minor versions

[NuGet] Publish nuget packages of .NET 8 rc2

---

.editorconfig
Extensions/CommandLine/tests/CommandArgumentTests.cs

- refactor for more readabilities

[Extensions] Fixed command line extension unit tests code smell

---

Cryptography/tests/HashRandomTests.cs
Detection/samples/Main/Pages/Error.cshtml.cs

- Not Null on int is unnecessary

[Cryptography] Fixed unnecessary unit assertion

---

Extensions/CommandLine/tests/CommandLineApplicationTests.cs
sonar-begin.ps1

- fixed code smell for better maintainability

[Extension] Fixed command line application unit tests

---

Blazor/samples/blazor-auto/Host.BlazorAuto.Client/Host.BlazorAuto.Client.csproj
Blazor/samples/blazor-auto/Host.BlazorAuto/Host.BlazorAuto.csproj
Blazor/samples/blazor-wasm/Host.BlazorWasm.csproj
Blazor/samples/blazor-wasm/wwwroot/index.html
Blazor/samples/server/Host.BlazorServer.csproj
Blazor/samples/server/Program.cs
Blazor/src/Components/Wangkanai.Blazor.Components.csproj
Blazor/src/Web/Wangkanai.Blazor.Components.Web.csproj
Directory.Build.targets
System/benchmark/CheckNumericBenchmark.cs
System/benchmark/CheckStringBenchmark.cs
System/benchmark/ForLoopBenchmark.cs
System/benchmark/MathBenchmark.cs
System/benchmark/Program.cs
System/benchmark/StringSpanVsSubstringBenchmark.cs

[Blazor] Fixed sample blazor server and web assembly

---

Extensions/CommandLine/tests/CommandLineApplicationTests.cs
Extensions/CommandLine/tests/CommandOptionTests.cs
Extensions/Internal/src/CoercedAwaitableInfo.cs
Extensions/Internal/src/ObjectMethodExecutor.cs
Extensions/Internal/src/ObjectMethodExecutorFSharpSupport.cs

https://sonarcloud.io/project/issues?open=AYsDUznft1PlUhiQzSAx&id=wangkanai_wangkanai

[Extensions] Converting possible null value to non-nullable type

---

Web/src/Server/Components/Layout/MainNavbar.razor
Web/src/Server/Components/Pages/About.razor
Web/src/Server/Components/Pages/Architecture.razor
Web/src/Server/Components/Pages/Blog.razor
Web/src/Server/Components/Pages/Design.razor
Web/src/Server/Components/Pages/Development.razor
Web/src/Server/Components/Pages/Engineering.razor
Web/src/Server/Components/Pages/Font.razor
Web/src/Server/Components/Pages/Terms.razor
Web/src/Server/Wangkanai.Web.csproj

[Web] update web navbar menu

---

Tabler/samples/Server/package.json

tabler icon is split into its own npm package

[Tabler] Update npm package webfont

---

Detection/tests/TagHelpers/BrowserTagHelperTests.cs
Extensions/Internal/tests/TypeNameHelperTests.cs

- Disable the fail unit tests and publish first

[Unit Test] Fix failed unit tests

---

Analytics/Directory.Build.props
Blazor/Directory.Build.props
Cryptography/Directory.Build.props
Detection/Directory.Build.props
Domain/Directory.Build.props
EntityFramework/Directory.Build.props
Extensions/Directory.Build.props
Federation/Directory.Build.props
Hosting/Directory.Build.props
Identity/Directory.Build.props
Markdown/Directory.Build.props
Mvc/Directory.Build.props
Responsive/Directory.Build.props
Security/Directory.Build.props
Solver/Directory.Build.props
System/Directory.Build.props
Tabler/Directory.Build.props
Testing/Directory.Build.props
Tools/Directory.Build.props
Validation/Directory.Build.props
Webmaster/Directory.Build.props
Webserver/Directory.Build.props
sign.ps1

- to align with .NET 8 public release

[Nuget] publish new nuget package

---

System/tests/Extensions/Strings/StringTrimTests.cs
System/tests/Extensions/Strings/StringUnicodeTests.cs

fixed up the string unit tests

[System] refactor & reformat string unicode unit tests code smell

---

System/src/Collections/ReverseComparer.cs
System/src/Extensions/QueryableExtensions.cs

- fixed warning CS8767 reverse comparer

[System] Fixed system collection code smell

---

System/sign.ps1
System/src/Checks/ThrowIfNullOrEmptyExtensions.cs
System/src/Checks/ThrowIfNullOrWhitespaceExtensions.cs
System/src/Checks/ThrowIfWhitespaceExtensions.cs
sign.ps1

[System] Fix check for null compiler warning

---

Analytics/sign.ps1
Blazor/sign.ps1
Cryptography/sign.ps1
Detection/sign.ps1
Domain/sign.ps1
EntityFramework/sign.ps1
Extensions/sign.ps1
Federation/sign.ps1
Hosting/sign.ps1
Identity/sign.ps1
Markdown/sign.ps1
Mvc/sign.ps1
Responsive/sign.ps1
Security/sign.ps1
Solver/sign.ps1
System/Directory.Build.props
Tabler/sign.ps1
Testing/sign.ps1
Tools/MSBuild/sign.ps1
Tools/Watcher/sign.ps1
Tools/sign.ps1
Validation/sign.ps1
Webmaster/sign.ps1
Webserver/sign.ps1
sign.ps1

- conditional dry run bool fix
- refactor tools sign into loop
- extensions & tools sign directory filters 'signed' & 'artifacts'

[System] Refactor powershell sign and publish

---

System/src/Collections/DictionaryByType.cs

[System] Fix dictionary compiler error

---

System/src/Reflection/PropertyCopy.cs

- refactor the code
- fixed compiler warning

[System] Fixed system reflection copy Property

---

System/src/Checks/ThrowIfNullGenericExtensions.cs
System/src/Checks/ThrowIfNullObjectExtensions.cs
System/src/Domain/AbstractTypeFactory.cs
System/src/Domain/GenericTypeInfo.cs

[System] Domain fixed possible null return

---

System/Directory.Build.props

[System] Publish 4.0 preview 2

---

System/src/Collections/RandomAccessQueue.cs
System/src/Extensions/AssemblyExtensions.cs
System/src/Extensions/CollectionExtension.cs
System/src/Extensions/DictionaryExtension.cs
System/src/Extensions/EnumExtensions.cs
System/src/Extensions/EnumValues.cs
System/src/Extensions/EnumerableExtensions.cs
System/src/Extensions/ObservableCollectionExtensions.cs
System/src/Extensions/SerializationExtensions.cs

- warning CS8603 possible null

[System] fixed extensions compiler warning

---

Validation/Directory.Build.props
Validation/benchmark/Wangkanai.Validation.Benchmark.csproj
Validation/src/RequireDigitAttribute.cs
Validation/src/RequireFalseAttribute.cs
Validation/src/RequireLowercaseAttribute.cs
Validation/src/RequireNonAlphanumericAttribute.cs
Validation/src/RequireTrueAttribute.cs
Validation/src/RequireUniqueCharAttribute.cs
Validation/src/RequireUppercaseAttribute.cs
Validation/src/Wangkanai.Validation.csproj
Validation/tests/Wangkanai.Validation.Tests.csproj

- warning CS8765: Nullability of type of parameter 'value' doesn't match overridden member (possibly because of nullability attributes)

[Validation] Resolve build warning and code smell

---

System/Directory.Build.props
System/tests/Attributes/DeprecateAttributeTests.cs
System/tests/Checks/CheckBooleanTests.cs
System/tests/Checks/CheckCompareTests.cs
System/tests/Checks/CheckEmptyStringTests.cs
System/tests/Checks/CheckIndexRangeTests.cs
System/tests/Checks/CheckNullTests.cs
System/tests/Checks/CheckNumericTests.cs
System/tests/Checks/CheckStringTests.cs
System/tests/MathTests.cs
System/tests/RandomGenerator.cs
Validation/Directory.Build.props

[System] update preview version

---

System/tests/Collections/ComparisonComparerTests.cs
System/tests/Collections/RandomAccessQueueTests.cs
System/tests/Extensions/CollectionExtensionsTests.cs
System/tests/Reflection/PropertyCopyTests.cs

warning CS8618: Non-nullable property 'First' must contain a non-null value when exiting constructor. Consider declaring the property as nullable.

[System] fixed unit tests

---

System/tests/Collections/RandomAccessQueueTests.cs
System/tests/Domain/AbstractTypeFactoryTests.cs
System/tests/Extensions/CollectionExtensionsTests.cs
System/tests/Extensions/Strings/StringSlashTests.cs
System/tests/Extensions/Strings/StringSplitTests.cs
System/tests/Extensions/Strings/StringSubstringTests.cs
System/tests/RandomGenerator.cs
System/tests/StaticRandomTests.cs
sonar-begin.ps1
sonar-prep.ps1

warning CS8618: Non-nullable field '_numbers' must contain a non-null value when exiting constructor. Consider declaring the field as nullable.

[System] Resolve unit tests warning

---

System/Directory.Build.props
Validation/Directory.Build.props
sign.ps1

- public release of system with .net 8.0

[System] Publish System package 4.0 rtm

---

Detection/samples/Main/Host.Main.csproj
Extensions/Directory.Build.props
Extensions/Internal/src/ObjectMethodExecutorFSharpSupport.cs
Extensions/Internal/src/TypeNameHelper.cs
Extensions/Internal/tests/TypeNameHelperTests.cs
Federation/hosts/EntityFramework/Host.EntityFramework.csproj
System/src/Checks/ThrowIfEmptyStringExtensions.cs
System/src/Checks/ThrowIfNullExtensions.cs
System/tests/Reflection/PropertyCopyTests.cs
Tabler/src/Web/Wangkanai.Tabler.Components.Web.csproj
Web/src/Server/Wangkanai.Web.csproj
sign.ps1

- ObjectMethodExecutorFSharpSupport.cs(37,37): warning CS8604: Possible null reference argument for parameter 'possibleFSharpAsyncGenericType' in 'bool ObjectMethodExecutorFSharpSupport.IsFSharpAsyncOpenGenericType(Type possibleFSharpAsyncGenericType)'.
- TypeNameHelperTests.cs(10,14): warning xUnit1013: Public method 'GetTypeDisplayName_ReturnsFriendlyName' on test class 'TypeNameHelperTests' should be marked as a Fact. Reduce the visibility of the method, or add a Fact attribute to the method. (https://xunit.net/xunit.analyzers/rules/xUnit1013)

[Extensions] Resolve extensions build warnings

---

Testing/Directory.Build.props
Testing/src/Builders/AssertionBuilder.cs
Testing/src/DependencyInjection/AssertionBuilderExtensions.cs
Testing/src/DependencyInjection/AssertionCollectionExtensions.cs
Testing/src/Services/AssertionMarkerService.cs
Testing/src/Services/AssertionService.cs
Testing/src/Services/Interfaces/IAssertionService.cs
Testing/src/Services/Interfaces/IScopedService.cs
Testing/src/Services/Interfaces/ISingletonService.cs
Testing/src/Services/Interfaces/ITransientService.cs

- confirm that all the warnings are clear on build

[Testing] prepare to publish preview1

---

Cryptography/Directory.Build.props
Cryptography/src/Hash.cs
Cryptography/tests/HashTests.cs

- clear all build warnings
- add hash unit tests

[Cryptography] Prepare to publish preview1

---

Directory.Packages.props
Tools/Directory.Build.props
Tools/MSBuild/src/Wangkanai.MSBuild.csproj
Tools/Watcher/src/Wangkanai.Watcher.csproj
sonar-begin.ps1
sonar-prep.ps1

- publish sign nuget packages
- update the sonar version

Publish NuGet Packages

---

sign.ps1

A line has been added to "sign.ps1" to include the "powershell-env.ps1" file. A comment line has also been amended in the same file.

Include "powershell-env.ps1" in sign.ps1

---

.editorconfig
Directory.Build.targets
Security/samples/Razor/Controllers/VersionController.cs
System/src/Extensions/AssemblyExtensions.cs
System/src/Extensions/AttributeExtensions.cs
System/src/Extensions/CollectionExtension.cs
System/src/Extensions/ComparerExtensions.cs
System/src/Linq/ExpressionFactory.cs
System/tests/Extensions/AssemblyExtensionsTests.cs
System/tests/Extensions/AttributeExtensionsTests.cs
System/tests/Extensions/CollectionExtensionsTests.cs
System/tests/Wangkanai.System.Tests.csproj
Tabler/samples/Old/Pages/Layouts/Boxed.razor
Tabler/samples/Old/package.json

A new test class AssemblyExtensionsTests has been added. In CollectionExtensionsTests, the list assignments were streamlined for readability. Code in ExpressionFactory was also refactored to remove redundant statements and for improved readability.

Add AssemblyExtensionsTests and refactor code

---

Directory.Packages.props

The package versions in Directory.Packages.props file have been updated along with the implementation of dynamic versioning. The version numbers are now defined at the beginning of the file and referred to throughout, enabling more efficient updates in the future.

Update package versions and implement dynamic versioning

---

System/tests/StaticRandomTests.cs

Expanded and refined the suite of unit tests for the StaticRandom class. This includes improving the validation of random double generation and adding new tests for different methods like Next, NextBytes, NextBytesSpan to ensure randomness.

Enhance StaticRandom tests

---

System/src/Decorator.cs
System/src/Math.cs
System/src/StaticRandom.cs
System/tests/MathTests.cs
System/tests/StaticRandomTests.cs

Documentation is crucial for any software project. It helps maintainers, contributors, and users understand the purpose of the code, how it works, and how to use it. Good documentation can significantly reduce the learning curve for new contributors, facilitate the onboarding process, and improve the overall quality of the project.
Pull Request Summary:
Title: Improve Documentation for Better Code Understanding
Description:
This pull request aims to enhance the documentation of our project. The changes include adding more detailed comments to our classes and methods, updating the README file with more comprehensive instructions, and providing examples where necessary.
The importance of good documentation cannot be overstated. It serves as a guide for new contributors, helping them …

Add documentation for System library 

---

Annotations/Directory.Build.props
Annotations/README.md
Annotations/benchamrk/ForeachBenchmark.cs
Annotations/benchamrk/Program.cs
Annotations/benchamrk/Wangkanai.Annotations.Benchmark.csproj
Annotations/build.ps1
Annotations/sign.ps1
Annotations/src/Wangkanai.Annotations.csproj
Annotations/tests/Wangkanai.Annotations.Tests.csproj
Wangkanai.sln

This commit introduces Wangkanai Annotations as a new project, including its associated tests, benchmarks, and related files such as build scripts and README. Further adjustments have been made to the solution file to incorporate these new projects.

Add Wangkanai Annotations and associated tests/benchmarks

---

System/src/Collections/DictionaryByType.cs
System/src/Collections/LinkedComparer.cs
System/src/Collections/ProjectionComparer.cs
System/src/Collections/ProjectionEqualityComparer.cs
System/src/Collections/RandomAccessQueue.cs
System/src/Collections/Range.cs
System/tests/Collections/ProjectionEqualityComparerTests.cs
System/tests/Collections/RangeTests.cs

In this commit, the ProjectionEqualityComparer class has been refactored for better readability and maintainability. Additional tests have also been added providing more comprehensive coverage. Minor typo fixes and text improvements were also made across multiple files.

Refactor ProjectionEqualityComparer, enhance tests, and fix typo errors

---

Directory.Packages.props
Federation/hosts/EntityFramework/Host.EntityFramework.csproj
Tabler/samples/Server/Host.Main.csproj
Tabler/src/Web/Wangkanai.Tabler.Components.Web.csproj
Web/src/Server/Wangkanai.Web.csproj

This update changes the version numbers for various packages used in the project, including Microsoft.AspNetCore, Microsoft.Extensions, Microsoft.EntityFrameworkCore, and Microsoft.IdentityModel, as well as test-related packages like xunit and Microsoft.NET.Test.Sdk. All versions have been updated to the latest stable version to incorporate new features and bug fixes.

Update package versions in Directory.Packages.props

---

System/tests/Extensions/StreamExtensionsTests.cs

The code in StreamExtensionsTests.cs was updated to handle null values correctly. Specifically, we now assert that an ArgumentNullException is thrown if the stream is null. The Stream variable declaration was also adjusted to allow nullable types.

Update null handling in StreamExtensionsTests

---

Detection/tests/Mocks/MockServer.cs
Detection/tests/Mocks/MockService.cs
Hosting/src/Extensions/StringExtensions.cs
Hosting/tests/ApplicationBuilderExtensionTests.cs
Hosting/tests/Mocks/MockServer.cs
Hosting/tests/StringExtensionTests.cs
Responsive/src/DependencyInjection/ResponsiveApplicationExtensions.cs
Responsive/tests/Mocks/MockClient.cs
Responsive/tests/Mocks/MockPageRouteModel.cs
Responsive/tests/Mocks/MockServer.cs
Responsive/tests/Mocks/MockService.cs

Added new unit tests for `StringExtensionTests` and `ApplicationBuilderExtensionTests`. Refactored the existing code in `StringExtensions.cs` and made it more succinct in `MockServer.cs`. Also introduced a new `MockServer.cs` for Wangkanai.Hosting namespace for testing purposes.

Add unit tests and refactor existing code

---

Federation/src/Domain/Models/AbstractResource.cs
Federation/src/Domain/Models/FederationApi.cs
Federation/src/Domain/Models/FederationResource.cs
Federation/src/Domain/Models/FederationScope.cs
Federation/src/Domain/Models/Resource.cs

Resource is the basic unit of all federal resources that reiterate from this abstract class. Therefore, we need a clear defined strategy to encapsulate this resource.

Refactor class FederationResource to Resource

---

Wangkanai.sln

The LICENSE file is now included in the solution for better visibility and compliance. This ensures that the license is readily accessible for contributors and users.

Add LICENSE file to solution structure

---

Annotations/Directory.Build.props
Annotations/README.md
Annotations/src/NegativeIntegerAttribute.cs
Annotations/src/PositiveIntegerAttribute.cs
Annotations/src/ZeroIntegerAttribute.cs
Detection/tests/Services/PlatformServiceTests.cs
Federation/src/Federation/Validations/ValidationRequest.cs

- Updated `Annotations` README for clearer usage guidelines.  
- Improved package metadata to reduce false positive warnings and enhance code purity.  
- Adjusted nullability specifications and API semantics for more precise integration.  
- Upgraded version to `0.3.0` to reflect significant improvements.  
- Replaced outdated tags with more relevant terms for better alignment.

Refine documentation and metadata for improved clarity  

---

.editorconfig
.github/copilot-instructions.md
Directory.Packages.props
Domain/Directory.Build.props
Domain/src/AuditTrail.cs
Domain/src/Entity.cs
Domain/src/TrackingEntry.cs
Domain/src/TrailType.cs
Domain/src/Wangkanai.Domain.csproj
Domain/tests/AuditTrailTests.cs
Wangkanai.sln

This pull request introduces two key updates:
- **`TrailType` enum:** Defines action types with values `None`, `Create`, `Update`, and `Delete`.
- **`AuditTrail` class:** Includes a `TrailType` property to facilitate tracking changes effectively.
These updates lay the groundwork for consistent tracking of operations.

Add TrailType enum and AuditTrail class

---

Domain/src/AuditTrail.cs
Domain/src/Configurations/AuditTrailConfiguration.cs
Domain/tests/AuditTrailTests.cs
Domain/tests/Configurations/AuditTrailConfigurationTests.cs
System/tests/StaticRandomTests.cs

This pull request refactors the `AuditTrail` class for better clarity and maintainability. Key changes include:
- Renamed the `Type` property to `TrailType` to improve naming consistency.
- Added `AuditTrailConfiguration` to define EF Core mappings.
- Enabled `jsonb` support for storing changed columns and tracking value changes.
- Minor formatting adjustments in property declarations.
These changes aim to improve readability, clarity, and functionality of the `AuditTrail` class.

Refactor AuditTrail and enhance EF Core configuration

---

Domain/Directory.Build.props
System/Directory.Build.props
sign.ps1

Change the version prefix in the project configuration to reflect the new version.

Update version prefix to 5.2.0

---

Directory.Build.props
Directory.Packages.props

Updated the copyright year in `Directory.Build.props` to 2025 to ensure project metadata remains accurate and current.

Update copyright year to 2025

---

.github/workflows/dotnet.yml
Tabler/src/Web/package.json

This pull request includes updates to the `Tabler/src/Web/package.json` file to ensure dependencies are up-to-date.
Dependency updates:
* Updated `@tabler/core` from version `^1.0.0-beta20` to `^1.2.0`.
* Updated `nodemon` from version `^3.1.0` to `^3.1.9`.
* Updated `sass` from version `^1.72.0` to `^1.86.3`.

Tabler NPM package update dependencies

---

Directory.Packages.props

This pull request updates package versions in the `Directory.Packages.props` file to ensure consistency and to include the latest versions of dependencies. The changes primarily focus on aligning versions with defined variables and upgrading specific packages.
* Updated `Microsoft.Extensions.DependencyInjection.Abstractions` to use the `$(ExtensionsVersion)` variable for consistency with other related packages.
* Updated `Microsoft.AspNetCore.TestHost` to use the `$(FrameworkVersion)` variable instead of a fixed version (`8.0.0`).
* Upgraded `HtmlAgilityPack` from version `1.12.0` to `1.12.1` to include the latest patch release.

NuGet package upgrade

---

.editorconfig
.github/workflows/qodana_code_quality.yml
qodana.yaml

This pull request updates the Qodana workflow to improve consistency and streamline artifact archiving.
*   Updated `.editorconfig` with adjusted indentation settings for YAML files and refined file header templates.
*   Modified Qodana workflow arguments and added artifact archiving steps.
*   Specified SARIF upload steps.
<commit>Update .editorconfig and Qodana GitHub workflow settings</commit>

Update Qodana workflow settings.

---

.github/workflows/dotnet.yml
.github/workflows/qodana_code_quality.yml
README.md

Implement Qodana code coverage update
This pull request addresses an issue with the Qodana workflow's code coverage artifact upload path.
-   Updated the path to ensure accurate code coverage capture and upload.

Qodana Code Coverage and wildcard path

---

System/Directory.Build.props

Incremented the VersionPrefix from 5.4.0 to 5.5.0 to reflect the latest changes or enhancements. Ensures the build system is aligned with the updated project versioning.

Update version to 5.5.0 in Directory.Build.props

---

Directory.Build.props
Domain/Directory.Build.props
Domain/README.md
Domain/src/AuditTrail.cs
Domain/src/TrailType.cs

This pull request makes minor documentation updates to improve code readability and consistency in the `Domain` namespace. It updates XML documentation comments in two files.
* [`Domain/src/AuditTrail.cs`](diffhunk://#diff-14eeb07f056f025bc3e9270eae8fe8deaa963279a9629ac1ee6876226565f46bL7-R7): Reformatted the XML documentation comment for the `AuditTrail` class to use a single-line summary format.
* [`Domain/src/TrailType.cs`](diffhunk://#diff-217cf59403e61da700772b6e376c5634103fe0a4465dac7641636f3cde214b8eR5): Added a new XML documentation comment for the `TrailType` enum to describe its purpose.

Refactor code documentation for audit trail components

---

Domain/src/Configurations/AuditConfiguration.cs
Domain/src/Extensions/AuditContextExtensions.cs
Domain/src/Stores/AuditStore.cs
Domain/src/Stores/IAuditStore.cs
Domain/src/Stores/IQueryableAuditStore.cs
Domain/tests/Configurations/AuditConfigurationTests.cs
Domain/tests/Extensions/AuditContextExtensionsTests.cs
Domain/tests/Stores/AuditStoreTests.cs

This pull request refactors and enhances the `AuditStore` and related interfaces by renaming properties for consistency, implementing previously unimplemented methods, and improving method signatures for better nullability handling. The changes also include detailed XML documentation for improved code clarity.
* Renamed the `AuditTrails` property to `Audits` in both `AuditStore` and `IQueryableAuditStore` for consistency. Similarly, renamed the backing field `AuditTrailsSet` to `AuditsSet` in `AuditStore`. (`Domain/src/Stores/AuditStore.cs`, [[1]](diffhunk://#diff-3fa22d3363e8023e2643baa4734760ab614210dc48937220d93a7f24f5522575L25-R28); `Domain/src/Stores/IQueryableAuditStore.cs`, [[2]](diffhunk://#diff-6bee3709150302d7199ec2c163114e2d51b7c0820836e42b81a8bb75a953fc3cL18-R18)
* Fully …

[Domain] Audit Store implementation

---

.github/workflows/dotnet.yml

This pull request includes a small update to the `.github/workflows/dotnet.yml` file. The change adds a version parameter (`/v:1.0`) to the SonarCloud Scanner command to specify the version of the project being analyzed.

[CI] SonarCloud scanner configuration version parameter

---

SonarQube.Analysis.xml

This pull request includes updates to the `SonarQube.Analysis.xml` configuration file to modify exclusion properties for analysis and coverage. The changes primarily involve reformatting and commenting out certain properties for clarity and potential future use.
Updates to SonarQube exclusion properties:
* Reformatted the `sonar.exclusions` property by removing the `**/tests/**` pattern and commenting out the original line for potential reuse.
* Adjusted the `sonar.coverage.exclusions` property formatting without altering its content.

[CI] SonarQube exclusions configuration

---

Analytics/Directory.Build.props
Annotations/Directory.Build.props
Blazor/Directory.Build.props
Cryptography/Directory.Build.props
Detection/Directory.Build.props
Domain/Directory.Build.props
EntityFramework/Directory.Build.props
Extensions/Directory.Build.props
Federation/Directory.Build.props
Hosting/Directory.Build.props
Identity/Directory.Build.props
Markdown/Directory.Build.props
Microservice/Directory.Build.props
Mvc/Directory.Build.props
Nation/Directory.Build.props
Responsive/Directory.Build.props
Security/Directory.Build.props
Solver/Directory.Build.props
System/Directory.Build.props
Tabler/Directory.Build.props
Testing/Directory.Build.props
Tools/Directory.Build.props
Validation/Directory.Build.props
Webmaster/Directory.Build.props
Webserver/Directory.Build.props

This pull request updates the `VersionPrefix` property across multiple `Directory.Build.props` files for various Wangkanai libraries to reflect new version increments. These changes prepare the libraries for their next release cycle.
* **Analytics**: Updated version from `2.1.0` to `2.2.0` (`Analytics/Directory.Build.props`).
* **Annotations**: Updated version from `0.3.0` to `0.4.0` (`Annotations/Directory.Build.props`).
* **Blazor**: Updated version from `4.1.0` to `4.2.0` (`Blazor/Directory.Build.props`).
* **Cryptography**: Updated version from `1.2.0` to `1.3.0` (`Cryptography/Directory.Build.props`).
* **Detection**: Updated version from `8.17.0` to `8.18.0` (`Detection/Directory.Build.props`).
* **Domain**: Updated version from `5.0.0` to `5.1.0` (`Domain/Directory.Build.props`).
* …

Incremented `VersionPrefix` across multiple projects

---

repomix.config.json

This pull request updates the `repomix.config.json` file to modify configuration options for file processing, directory structure, and ignored patterns. The key changes include adjusting processing flags, expanding the list of file extensions and patterns to include or ignore, and adding a new output configuration.
* **File Processing Flags**: Changed `removeComments`, `removeEmptyLines`, and `compress` options from `true` to `false`. Increased `topFilesLength` from 15 to 20.
* **File Extensions and Patterns**:
- Expanded the list of included file extensions to support additional formats like `.ps1`, `.yml`, `.yaml`, `Dockerfile`, and others.
- Updated ignored patterns to include broader directories and file types such as `node_modules`, `.vscode`, `.idea`, log files, and temporary files. …

Update repomix.config.json to modify file handling and ignore patterns

---

API_DOCUMENTATION_TEMPLATE.md
BUILD_GUIDE.md
DOCUMENTATION_NAVIGATION.md
PROJECT_INDEX.md
System/src/Extensions/CollectionExtension.cs
System/src/Extensions/StringExtensions.cs
WANGKANAI_MODULE_ANALYSIS.md
Wangkanai.slnx
build-enhanced.ps1
build-simple.ps1

This pull request introduces extensive documentation improvements and organizational enhancements for the Wangkanai libraries. The changes include a new API documentation template, a navigation guide for documentation, and a detailed module analysis report. These updates aim to standardize and improve the quality of documentation across all modules.
* **API Documentation Template**: Added a comprehensive template (`API_DOCUMENTATION_TEMPLATE.md`) to ensure consistent and detailed API documentation for all Wangkanai libraries. The template includes sections for installation, configuration, core APIs, advanced usage, error handling, performance considerations, and migration guides.
* **Documentation Navigation Guide**: Introduced a navigation guide (`DOCUMENTATION_NAVIGATION.md`) outlining …

Add comprehensive API documentation template and navigation guide
