- README.md
- sample/Device/Controllers/HomeController.cs
- sample/Device/Views/Home/Index.cshtml
- sample/Sandbox/Controllers/HomeController.cs
- src/Wangkanai.Detection.Browser/BrowserHttpRequestExtensions.cs
- src/Wangkanai.Detection.Core/UserAgentService.cs
- src/Wangkanai.Detection.Crawler/CrawlerHttpRequestExtensions.cs
- src/Wangkanai.Detection.Device/DeviceHttpRequestExtensions.cs
- src/Wangkanai.Detection.Engine/EngineHttpRequestExtensions.cs
- src/Wangkanai.Detection.Platform/PlatformHttpRequestExtensions.cs
- test/Wangkanai.Detection.Crawler.Test/CrawlerTest.cs
- test/Wangkanai.Detection.Test/DetectionServiceTests.cs
Adding extensible to existing usage scenario is a key design. So I would like to propose a concept of extending the `HttpRequest` for developer to access the `Browser`, `Device`, `Platform`, `Engine` directly. This extension then retrieve the instance from the `BrowserService`.
``` csharp
var browser = Request.Browser();
var platform = Request.Platform();
var device = Request.Device();
var engine = Request.Engine();
var crawler = Request.Crawler();
```
Example of usage
```csharp
public IActionResult Index()
{
ViewData["Device"] = Request.Device().Type;
return View(_resolver);
}
```
> #1 Add extensions to HttpRequest

- src/Detection.Browser/src/Collections/InternetExplorer.cs
- src/Detection.Browser/test/BrowserResolverTests.cs
Extend IE detection to resolve issue where IE11 on Windows 10 is detected as Generic.
Approach:
- Check for "Trident/" and "rv:11.0" in the user agent string
Addresses #62
> Add detection for IE 11 on Windows 10

- src/DependencyInjection/BuilderExtensions/Core.cs
- src/Extensions/EnumerableExtensions.cs
- src/Extensions/VersionExtensions.cs
- src/Services/PreferenceService.cs
- src/Services/UserAgentService.cs
- test/Services/DetectionServiceTests.cs
Also giving services with direct dependency injection of `HttpContextAccessor`. So their don't need to go through of UserAgentService every time.
> Remove depend on HttpContextExtensions

- sample/Responsive/Views/Home/Index.cshtml
- src/TagHelpers/BrowserTagHelper.cs
- src/TagHelpers/CrawlerTagHelper.cs
- src/TagHelpers/EngineTagHelper.cs
- src/TagHelpers/PlatformTagHelper.cs
```html
<section id="device">
<h3>device</h3>
<h5>desktop</h5>
<device include="desktop">is desktop</device>
<device exclude="desktop">not desktop</device>
<h5>tablet</h5>
<device include="tablet">is tablet</device>
<device exclude="tablet">not tablet</device>
<h4>mobile</h4>
<device include="mobile">is mobile</device>
<device exclude="mobile">not mobile</device>
</section>
<section id="browser">
<h3>browser</h3>
<h5>google chrome</h5>
<browser include="chrome">is chrome</browser>
<browser exclude="chrome">not chrome</browser>
<h5>microsoft edge</h5>
<browser include="edge">is edge</browser>
<browser exclude="edge">not edge</browser>
</section>
<section id="platform">
<h3>platform</h3>
<h5>microsoft windows</h5>
<platform include="windows">is windows</platform>
<platform …
```
> Responsive TagHelpers completed

- sample/Detection/Pages/Index.cshtml
- sample/DetectionOld/Views/Home/Index.cshtml
- src/Services/BrowserService.cs
- src/Services/CrawlerService.cs
- src/Services/EngineService.cs
- src/Services/Interfaces/IBrowserService.cs
- src/Services/Interfaces/ICrawlerService.cs
- src/Services/Interfaces/IDetectionService.cs
- src/Services/Interfaces/IDeviceService.cs
- src/Services/Interfaces/IEngineService.cs
- src/Services/Interfaces/IPlatformService.cs
- src/Services/Interfaces/IUserAgentService.cs
- src/Services/PlatformService.cs
- src/TagHelpers/BrowserTagHelper.cs
- src/TagHelpers/CrawlerTagHelper.cs
- src/TagHelpers/EngineTagHelper.cs
- src/TagHelpers/PlatformTagHelper.cs
- test/Services/BrowserServiceTest.cs
- test/Services/CrawlerServiceTest.cs
- test/Services/EngineServiceTest.cs
- test/Services/PlatformServiceTest.cs
I believe that using the property as `Type` may cause miss understanding that this is `System.Type`. When its suppose to mean the name of the technology that the client request is using.
```html
<ul>
<li>@Detection.Device?.Type</li>
<li>@Detection.Browser?.Name</li>
<li>@Detection.Platform?.Name</li>
<li>@Detection.Engine?.Name</li>
</ul>
```
> Resolver services determine the Name not the Type

- src/DependencyInjection/BuilderExtensions/Core.cs
- src/Extensions/EnumExtensions.cs
- src/Extensions/UserAgentExtensions.cs
- src/Models/Platform.cs
- src/Services/BrowserService.cs
- src/Services/EngineService.cs
- src/Services/Interfaces/IPlatformService.cs
- src/Services/PlatformService.cs
- src/TagHelpers/DeviceTagHelper.cs
- test/DependencyInjection/ApplicationBuilderExtensionsTest.cs
- test/DependencyInjection/BuilderExtensions/Responsive.csTest.cs
- test/Hosting/PreferenceSessionTests.cs
- test/Mocks/MockServer.cs
- test/Services/PlatformServiceTest.cs
Their is a conflict with `System.OperatingSystem` and our `Wangkanai.Detection.Models.OperatingSystem`. Therefore, its better to change it to Platform that reflect more to our domain.
> Change OperatingSystem to Platform

- Detection.sln
- Wangkanai.Benchmarks/Program.cs
- Wangkanai.Benchmarks/Wangkanai.Benchmarks.csproj
- src/Collections/MobileCollection.cs
- src/Collections/TabletCollection.cs
- src/Extensions/UserAgentExtensions.cs
- src/Models/UserAgent.cs
I've added benchmarks project and improved device detection hot path performance.
Core idea: 
- do not lowercase user agent string for every check (major perf boost)
- do not allocate delegates on array comparison (minor perf boost)
Hardware and Software
```
BenchmarkDotNet=v0.12.1, OS=Windows 10.0.17763.1158 (1809/October2018Update/Redstone5)
Intel Core i5-3570K CPU 3.40GHz (Ivy Bridge), 1 CPU, 4 logical and 4 physical cores
.NET Core SDK=3.1.102
[Host]  : .NET Core 3.1.2 (CoreCLR 4.700.20.6602, CoreFX 4.700.20.6702), X64 RyuJIT
LongRun : .NET Core 3.1.2 (CoreCLR 4.700.20.6602, CoreFX 4.700.20.6702), X64 RyuJIT
```
Before:
| Method |     Mean |    Error |   StdDev |   Gen 0 | Gen 1 | Gen 2 | Allocated |
|------- |---------:|---------:|---------:|--------:|------:|------:|----------:|
| …
> Benchmarks and performance improvements

- src/DependencyInjection/BuilderExtensions/Core.cs
- src/Services/ResponsiveService.cs
I am not sure about this one, seems like nothing prevents scoped registration unless I've missed something.
This should help reduce allocations in the scenario when detection services are injected by user code in several places during request lifetime
> Transient to Scoped registration for core services

- src/Services/BrowserService.cs
- test/DependencyInjection/BuilderExtensions/CoreTest.cs
Better not to reinvent the wheel and reuse the already resolve browser name.
```csharp
private static Version GetVersion(string agent, Browser browser) {}
```
> Browser Service change to Enum for GetVersion()

- src/Extensions/HttpContextExtensions.cs
- src/Extensions/UserAgentExtensions.cs
- src/Models/Platform.cs
- src/Models/UserAgent.cs
- src/Services/BrowserService.cs
- src/Services/PlatformService.cs
- src/Wangkanai.Detection.csproj
- test/Services/PlatformServiceTest.cs
I have split the iOS and iPadOS platform out from each other. While this a breaking changes in the platform enumeration index. But i think it a good upgrade.
> #488 iPadOS version parsing fixed

- src/Services/PlatformService.cs
- test/Services/PlatformServiceTest.cs
If platform is iOS or iPadOS, then the user agent must have AppleWebKit also.
#481 Reference
> #481 Bot axios edge case

- benchmark/Wangkanai.Detection.Benchmark.csproj
- src/Extensions/HttpContextExtensions.cs
- src/Services/EngineService.cs
- src/Services/HttpContextService.cs
- src/Wangkanai.Detection.csproj
- test/Services/EngineServiceTest.cs
- test/Wangkanai.Detection.Test.csproj
I experienced an issue using the tag helpers to differentiation between Edge Legacy and Edge Chromium as they are very different browsers. The proposed approach is to retain the Browser detected as Edge for both cases but differentiate them based on the engine. This PR will result in Edge Legacy returning Edge as the engine and Edge Chromium returning Blink as the engine. I find this makes it easier to handle differentiation of that major Edge change Microsoft made recently.
This PR also adds netcoreapp3.1 as one of the target frameworks - just because the app I'm working hasn't yet moved to net5.0.
> Modified the modelling of the Edge browser with different engines

- .obsidian/workspace
- Detection/Directory.Build.props
- Detection/src/Extensions/VersionExtensions.cs
- Detection/tests/Services/BrowserServiceTest.cs
#567 iPadOS - Apple typo causes detection as version zero
> Fixed iPadOS 15.7 broswer version zero

- System/src/Reflection/PropertyCopy.cs
- System/tests/Reflection/PropertyCopyTests.cs
A generic class which copies to its target type from a source type specified in the Copy method. The types are specified separately to take advantage of type inference on generic method arguments.
> Property copy reflection helper

- Analytics/Directory.Build.props
- Analytics/src/Wangkanai.Analytics.csproj
- Detection/Directory.Build.props
- Detection/src/Wangkanai.Detection.csproj
- Responsive/Directory.Build.props
- Responsive/src/Wangkanai.Responsive.csproj
As of December 13, 2022 Microsoft have end support for the .NET Core 3.1 We will follow this for us to enable to platform features.
https://dotnet.microsoft.com/en-us/platform/support/policy/dotnet-core
> #574 Remove netcoreapp3.1 from Detection

- Blazor/src/Components/Rendering/RendererSynchronizationContext.cs
- System/src/Check.cs
- Tabler/demo/Client/wwwroot/index.html
- Web/src/tsconfig.json
I'm find a way for create a readonly lock for a local variable
> [Blazor] testing out local variable of lock

- sonar-project.properties
We don't need code source coverage of the federation hosts test bed, its work similar to samples and demo.
> [Federation] Exclusion hosts/ from source coverage

- Webmaster/src/Constants.cs
- Webmaster/src/Routing/LanguageRouteContraint.cs
Not specifying a timeout for regular expressions can lead to a Denial-of-Service attack. Pass a timeout when using System.Text.RegularExpressions to process untrusted input because a malicious user might craft a value for which the evaluation lasts excessively long.
> [Webmaster] Regex require timeout to limit the execution time

- System/src/Collections/RandomAccessQueue.cs
A loop with at most one iteration is equivalent to the use of an if statement to conditionally execute one piece of code. If the initial intention of the author was really to conditionally execute one piece of code, an if statement should be used instead. If that was not the initial intention of the author, the body of the loop should be fixed to use the nested return, break or throw statements in a more appropriate way.
> [System] Refactor the containing loop to do more than one iteration

- System/src/Check.cs
- System/src/Extensions/StringExtensions.cs
- System/tests/CheckTests.cs
For clarity, all overloads of the same method should be grouped together. That lets both users and maintainers quickly understand all the current available options.
> [System] All 'ThrowIfNull' method overloads should be adjacent.

- System/src/Check.cs
- System/src/Extensions/StringExtensions.cs
- System/tests/Checks/CheckStringTests.cs
The check for null is now getting more complicated with each new edge case during my investigative journey. I find that we should have checking just for empty string. Also adding to this, an ArgumentEmptyException to go along with the check.
Then come the point of the instance activator of creating exception instance when the condition is found to be throw.
> [System] Check for null add empty only condition

- System/src/Check.cs
This is by design to check for null, so the compiler does not need to warn about
- CS8603 Possible null reference return.
- CS8604 Possible null reference argument.
> [System] disable intention null in `Check` warning

- System/src/Extensions/DateTimeFactory/DateTimeFactoryExtensions.cs
Always set the "DateTimeKind" when creating new "DateTime" instances
https://sonarcloud.io/project/issues?open=AYlCzJ9eN98Sj3fKAObN&id=wangkanai_wangkanai
> [System] Fixed Provide the "DateTimeKind" when creating this object

- System/src/Collections/RandomAccessQueue.cs
Rename parameter 'index' to 'arrayIndex' to match the interface declaration.
https://sonarcloud.io/project/issues?open=AYiOyH758PTBoU7GMNq5&id=wangkanai_wangkanai
Parameter names should match base declaration and other partial definitions
> [System] Rename parameter 'index' to 'arrayIndex' 

- Federation/src/Federation/Responses/Models/AuthorizeResponse.cs
Non-nullable property 'Request' must contain a non-null value when exiting constructor. Consider declaring the property as nullable.
https://sonarcloud.io/project/issues?open=AYiQOw-SGLfIxx_yfDfn&id=wangkanai_wangkanai
> [Federation] Non-nullable property 'Request' must contain a non-null

- Validation/tests/Models/BaseModel.cs
- Validation/tests/Models/DigitModel.cs
- Validation/tests/Models/LowercaseModel.cs
- Validation/tests/Models/NonAlphanumericModel.cs
- Validation/tests/Models/UniqueModel.cs
- Validation/tests/Models/UppercaseModel.cs
- Validation/tests/RequireBooleanTests.cs
- Validation/tests/RequireLowercaseTests.cs
- Validation/tests/RequireUppercaseTest.cs
- warning CS8618: Non-nullable property 'Password' must contain a non-null value when exiting constructor. Consider declaring the property as nullable.
> [Validation] Fixed unit tests build warnings]

- Extensions/Directory.Build.props
- Testing/Directory.Build.props
- Validation/Directory.Build.props
The version suffix 'preview3' was removed from the validation properties file. This change reflects the transition from the preview phase to the ready-to-release phase for this specific .NET Data Annotation library.
> Publish production ready .NET 8 NuGet packages

- Analytics/sign.ps1
- Blazor/sign.ps1
- Cryptography/sign.ps1
- Detection/Directory.Build.props
- Detection/sign.ps1
- Domain/sign.ps1
- EntityFramework/sign.ps1
- Extensions/sign.ps1
- Federation/sign.ps1
- Hosting/sign.ps1
- Identity/sign.ps1
- Markdown/sign.ps1
- Mvc/sign.ps1
- Responsive/sign.ps1
- Security/sign.ps1
- Solver/sign.ps1
- System/sign.ps1
- Tabler/sign.ps1
- Testing/sign.ps1
- Tools/sign.ps1
- Validation/sign.ps1
- Webmaster/sign.ps1
- Webserver/Directory.Build.props
- Webserver/sign.ps1
- sign.ps1
The sign.ps1 scripts have been updated across multiple projects (Blazor, Detection, Analytics, Cryptography) to include an optional 'name' parameter. This allows the users to specify a name while running the script. The root path has also been updated in sign.ps1 for general script improvements and better path handling.
> Add optional name parameter to sign scripts

- .editorconfig
- System/src/Attributes/DeprecateAttribute.cs
- System/src/Attributes/NotNullAttribute.cs
- System/src/Attributes/PositiveIntegerAttribute.cs
- System/src/Checks/ExceptionActivator.cs
- System/src/Checks/NullConditionalExtensions.cs
- System/src/Checks/ThrowIfEmptyEnumerableExtensions.cs
- System/src/Checks/ThrowIfEmptyStringExtensions.cs
- System/src/Checks/ThrowIfEqualExtensions.cs
- System/src/Checks/ThrowIfLessThanExtensions.cs
- System/src/Checks/ThrowIfMoreThanExtensions.cs
- System/src/Checks/ThrowIfNegativeExtensions.cs
- System/src/Checks/ThrowIfNotEqualExtensions.cs
- System/src/Checks/ThrowIfNullExtensions.cs
- System/src/Checks/ThrowIfNullGenericExtensions.cs
- System/src/Checks/ThrowIfNullObjectExtensions.cs
- System/src/Checks/ThrowIfNullOrEmptyExtensions.cs
- System/src/Checks/ThrowIfNullOrWhitespaceExtensions.cs
- System/src/Checks/ThrowIfOutOfRangeExtension.cs
- System/src/Checks/ThrowIfPositiveExtensions.cs
- System/src/Checks/ThrowIfWhitespaceExtensions.cs
- System/src/Checks/ThrowIfZeroExtensions.cs
- System/src/Wangkanai.System.csproj
The code has been refactored to use the [NotNull] annotation to enforce non-null values in various methods. This affects the ThrowIfNullExtensions, ThrowIfWhitespaceExtensions, ThrowIfEmptyStringExtensions, and several other classes. Additionally, unnecessary classes and files were deleted for cleanup.
> Refactor code to expect non-null values

- System/benchmark/CheckStringBenchmark.cs
- System/benchmark/Program.cs
The benchmark testing routine has been modified, disabling the 'StringSpanVsSubstringBenchmark' test and enabling the 'CheckStringBenchmark' test. Additionally, a new job runtime for .NET 8.0 was added in 'CheckStringBenchmark'.
> Switch benchmark tests and update job runtime

- System/src/Attributes/NegativeIntegerAttribute.cs
- System/src/Attributes/PositiveIntegerAttribute.cs
- System/src/Checks/NullConditionalExtensions.cs
- System/src/Checks/ThrowIfEmptyEnumerableExtensions.cs
- System/src/Checks/ThrowIfEqualExtensions.cs
- System/src/Checks/ThrowIfNullOrEmptyExtensions.cs
- System/src/Decorator.cs
- System/src/Extensions/StringExtensions.cs
- System/src/Reflection/PropertyCopy.cs
- System/tests/Checks/CheckBooleanTests.cs
- System/tests/Checks/CheckCompareTests.cs
- System/tests/Checks/CheckEmptyListTests.cs
- System/tests/Checks/CheckEmptyStringTests.cs
- System/tests/Checks/CheckIndexRangeTests.cs
- System/tests/Checks/CheckNullTests.cs
- System/tests/Checks/CheckNumericTests.cs
- System/tests/Checks/CheckStringTests.cs
- System/tests/Checks/CreateExceptionInstanceTests.cs
- Webserver/src/DependencyInjection/DecoratorServiceExtensions.cs
The null check methods TrueIfNull and FalseIfNull in the NullConditionalExtensions class have been updated. The input parameters no longer accept nullable types. Also, a warning for non-null parameters when exiting has been added.
> Update null check methods in NullConditionalExtensions

- System/sign.ps1
The default name parameter in the sign.ps1 script has been changed to reflect a more explicit identification. "Sarin Na Wangkanai" has been updated to "Open Source Developer, Sarin Na Wangkanai" for better transparency.
> Update default name in sign.ps1 script

- Detection/sign.ps1
- Detection/src/Services/PlatformService.cs
- Detection/tests/Services/PlatformServiceTests.cs
- System/Directory.Build.props
Simplified method implementation in PlatformService.cs by converting some methods into expression-bodied members. This reduces unnecessary boilerplate and enhances readability. Additionally, a new test case for Windows version detection was added to the PlatformServiceTests.cs to ensure accuracy and reliability of our service.
Ref: #955
> Refactor PlatformService and update tests

- Analytics/sign.ps1
- Blazor/sign.ps1
- Cryptography/sign.ps1
- Detection/Directory.Build.props
- Domain/sign.ps1
- EntityFramework/Directory.Build.props
- EntityFramework/sign.ps1
- Extensions/sign.ps1
- Federation/sign.ps1
- Hosting/sign.ps1
- Identity/sign.ps1
- Markdown/sign.ps1
- Mvc/sign.ps1
- Responsive/sign.ps1
- Security/sign.ps1
- Solver/sign.ps1
- Tabler/sign.ps1
- Testing/sign.ps1
- Tools/sign.ps1
- Validation/sign.ps1
- Webmaster/sign.ps1
- Webserver/sign.ps1
- sign.ps1
Multiple scripts have been updated to reflect the developer's full professional title. Furthermore, the casing of the 'Release' directory as used in the build and packing process has been corrected in several places to properly match the directory names.
> Update developer's name and correct casing in scripts

- Tabler/samples/Old/package.json
- Tabler/samples/Server/package.json
- Web/old/package.json
- Web/src/Server/package.json
The versions of several dependencies have been updated in package.json files within Web/src/Server and Web/old directories. Additionally, the 'postcss' dependency has been removed from the Web/src/Server directory. These changes in the code have been made to keep our repositories up-to-date with the latest versions and reduce potential vulnerabilities.
> Update package dependencies

- System/src/Extensions/DateTimeExtensions.cs
- System/tests/Extensions/DateTimeExtensionsTests.cs
The new file DateTimeExtensionsTests.cs has been added to test the Truncate method in DateTimeExtensions. It includes three different scenarios: normal use, zero timespan, and negative timespan. Additionally, the Truncate method has been adjusted to handle TimeSpan.Zero more efficiently by returning the original datetime parameter.
> Add DateTimeExtensions tests and update Truncate method

- System/src/Checks/ThrowIfEmptyEnumerableExtensions.cs
- System/src/Collections/ProjectionComparer.cs
- System/src/Extensions/CollectionExtension.cs
- System/tests/Extensions/CollectionExtensionsTests.cs
Refined the parameters of the AddRangeSafe and Replace collection extension methods to accept IEnumerable instead of ICollection. Also corrected a minor XML tag error in ProjectionComparer file. Adjusted the code block of AddRangeSafe for readability and accuracy in logic.
> Fix collection extensions add range safe

- sonar-begin.ps1
- sonar-prep.ps1
The version variable in both sonar-prep.ps1 and sonar-begin.ps1 has been updated to reflect the latest version, 2.3. This ensures the scripts are referring and working with the most recent version.
> Update version to 2.3 in sonar scripts

- System/src/Extensions/SpanExtensions.cs
- System/tests/Extensions/SpanExtensionsTests.cs
A new class called SpanExtensions has been introduced in the Extensions namespace. This class includes an IsEmpty method, which checks if a given span is empty by comparing its length to 0.
> Add SpanExtensions class with IsEmpty method

- System/src/Extensions/EnumerableExtensions.cs
- System/tests/Extensions/EnumerableExtensionsTests.cs
The changes primarily involved updating the method definitions within EnumerableExtensions.cs. This includes renaming the method IsNullOrEmpty to IsEmpty and introducing a new method to check if the list is null. Additionally, a non-null constraint was added on the parameters for better reliability and to suppress CS8777 warnings.
> Update EnumerableExtensions methods

- Detection/src/Extensions/SearchExtensions.cs
- Detection/src/Services/PlatformService.cs
- System/src/Extensions/EnumExtensions.cs
- System/src/Extensions/EnumValues.cs
- System/src/Extensions/FormattingExtensions.cs
- System/src/Extensions/ObservableCollectionExtensions.cs
- System/tests/Extensions/EnumExtensionsTests.cs
- System/tests/Extensions/EnumValuesTests.cs
Variable 'sizes' has been renamed to 'Sizes' to maintain code standard in FormattingExtensions.cs. Unnecessary null checks in ObservableCollectionExtensions.cs removed. Initialization of Dictionary and Array `Names` and `Values` respectively moved to bottom in EnumValues.cs for better readability and consistency.
> Enum refactor variable naming and function parameters 

- System/src/Extensions/BinaryScalingExtensions.cs
- System/tests/Extensions/BinaryScalingExtensionsTests.cs
The file and class have been renamed from FormattingExtensions to BinaryScalingExtensions to better align with the functionality. The Sizes array has also been updated to better represent binary scaling.
> Rename FormattingExtensions to BinaryScalingExtensions

- System/tests/Extensions/KeyValuePairExtensionsTests.cs
This commit introduces a new unit test file named KeyValuePairExtensionsTests.cs. The file contains tests that validate methods for creating new KeyValuePair objects with modified keys or values. This includes testing scenarios when KeyValuePair objects are null.
> Add KeyValuePairExtensions unit tests

- System/src/Extensions/StreamExtensions.cs
- System/tests/Extensions/StreamExtensionsTests.cs
This commit introduces unit tests in the StreamExtensionsTests file to assure that the methods of StreamExtensions class perform as expected. The tests cover the methods: CopyTo, ReadFully, and ReadToString, including cases with null streams.
> Add StreamExtensionsTests for StreamExtensions methods

- System/src/Extensions/TreeExtensions.cs
- System/tests/Extensions/TreeExtensionsTests.cs
This commit updates the `GetAncestors` method in the `TreeExtensions.cs` by adding 'this' keyword to make it an extension method. It also ensures coding style consistency by adjusting whitespace. Additionally, the `TreeExtensionsTests.cs` file is created to include unit tests for the `Traverse` method, ensuring the correct functionality of these methods.
> Refactor TreeExtensions and add relevant tests

- System/src/Domain/AbstractTypeFactory.cs
- System/tests/Domain/AbstractTypeFactoryTests.cs
Several new test methods were added to AbstractTypeFactoryTests.cs to improve test coverage for the AbstractTypeFactory class. Additionally, the AbstractTypeFactory.cs file was refactored and simplified by removing the TryCreateInstance function that accepted two parameters. Lastly, the FindTypeInfoByName method has been updated to use clear null checks.
> Add more test methods and refactor AbstractTypeFactory

- Detection/src/Models/Browser.cs
- Detection/src/Models/Crawler.cs
- Detection/src/Models/Device.cs
- Detection/src/Models/Engine.cs
- Detection/src/Models/Platform.cs
- Detection/src/Services/BrowserService.cs
- Detection/src/Services/CrawlerService.cs
- Detection/src/Services/DeviceService.cs
- Detection/src/Services/EngineService.cs
- Detection/src/Services/PlatformService.cs
- System/src/Extensions/EnumExtensions.cs
- System/src/Extensions/EnumValues.cs
The 'ToStringMistake' method replaced with 'ToLowerString' method across the codebase in 'BrowserService.cs', 'PlatformService.cs', 'CrawlerService.cs'. Also, some parts in 'CrawlerService.cs' were simplified for efficiency. This change provides consistency and readability in naming convention and improves overall code neatness in the mentioned files. The obsolete 'ToStringMistake' method in 'EnumExtensions.cs' was also commented out.
> Replace 'ToStringMistake' calls with 'ToLowerString' and simplify code

- Detection/src/Services/BrowserService.cs
- Detection/tests/Services/BrowserServiceTests.cs
Updated the BrowserService algorithm to correctly handle the Edge browser iteration, characterized by the "EdgA" string in the user agent. Furthermore, slight alterations have been made to the GetVersionSafariSafari method, fixing the string slicing operation.
ref: #954
> Update version handling in BrowserService

- System/src/Extensions/EnumExtensions.cs
The obsolete methods ToStringMistake, ContainsMistake, and ContainSingleMistake have been removed from the EnumExtensions class. This cleanup simplifies the code and avoids the usage of deprecated functionality.
> Remove obsolete methods from EnumExtensions

- System/src/Checks/NullConditionalExtensions.cs
- System/src/Checks/ThrowIfEmptyEnumerableExtensions.cs
- System/src/Checks/ThrowIfEmptyStringExtensions.cs
- System/src/Checks/ThrowIfEqualExtensions.cs
- System/src/Checks/ThrowIfLessThanExtensions.cs
- System/src/Checks/ThrowIfMoreThanExtensions.cs
- System/src/Checks/ThrowIfNegativeExtensions.cs
- System/src/Checks/ThrowIfNotEqualExtensions.cs
- System/src/Checks/ThrowIfNullExtensions.cs
- System/src/Collections/ComparisonComparer.cs
- System/tests/Checks/CheckCompareTests.cs
- System/tests/Checks/CheckNumericTests.cs
- System/tests/StaticRandomTests.cs
Expanded comments for ThrowIfEmptyEnumerableExtensions, ThrowIfEmptyStringExtensions, and NullConditionalExtensions to provide more information about each method's functionality. This will help the users to understand the purpose and usage of these extension methods more clearly.
> Add documentation toward System

- System/src/Collections/RangeIterator.cs
- System/src/Collections/ReverseComparer.cs
- System/src/Collections/StringArrayComparer.cs
- System/tests/Collections/RangeIteratorTests.cs
Changed all camel case variable names to Pascal case in 'RangeIteratorTests.cs' as part of the ongoing effort to enforce naming conventions and improve code readability.
> Update system documentations

- Hosting/Directory.Build.props
- Microservice/src/Wangkanai.Microservice.csproj
- sign.ps1
A new project reference to Wangkanai.Hosting.csproj has been added in Wangkanai.Microservice.csproj. The version prefix in Directory.Build.props has also been changed from 3.1.0 to 3.2.0. Additionally, a tweak has been made on the sign.ps1 script, specifically uncommenting the "System" directory.
> Added project reference and updated version prefix

- EntityFramework/Directory.Build.props
- EntityFramework/src/Generators/DateTimeNowGenerator.cs
- EntityFramework/src/Generators/DateTimeOffsetNowGenerator.cs
- sign.ps1
Added DateTimeNowGenerator and DateTimeOffsetNowGenerator classes in the Generators namespace to create DateTime and DateTimeOffset values when new entities are added in the EntityFramework context. These generators override Next method to throw an exception if entity is null or generate current timestamp otherwise.
> Add DateTimeNow and DateTimeOffsetNow entity generators

- Federation/src/Domain/Models/BaseResource.cs
- Federation/src/Domain/Models/FederationClient.cs
- Federation/src/Domain/Models/FederationCompany.cs
- Federation/src/Domain/Models/FederationDirectory.cs
- Federation/src/Domain/Models/FederationGroup.cs
- Federation/src/Domain/Models/FederationResource.cs
- Federation/src/Domain/Models/FederationTenant.cs
- Federation/tests/Domain/Models/FederationClientTests.cs
- Federation/tests/Domain/Models/FederationResourceTests.cs
Several new model classes have been introduced: FederationCompany, FederationDirectory, FederationGroup, FederationTenant, and FederationResourceTests. The FederationResource and FederationClient were modified, with the former extending a renamed class from AbstractResource to BaseResource. The modification in FederationClient involves adjusting the visibility of a private property.
> Add new model classes and revise existing ones

- Blazor/tests/MockTests.cs
- Directory.Packages.props
- EntityFramework/tests/DatabaseMigrationExtensions.cs
- EntityFramework/tests/FooDbContext.cs
- Identity/tests/MockTests.cs
- System/benchmark/Wangkanai.System.Benchmark.csproj
- System/tests/xunit.runner.json
- Testing/src/Wangkanai.Testing.csproj
- Testing/tests/MockTests.cs
This commit introduces a basic unit test for the Blazor project. The test validates a simple mock implementation to ensure foundational functionality is in place.
> Add initial unit test for Blazor mock functionality

- Detection/src/Extensions/KmpPrefixTrie.cs
- Detection/src/Extensions/PrefixTrie.cs
Replaced null checks with `TrueIfNull()` for clarity and consistency. Simplified collection initialization by swapping `Array.Empty<T>()` with shorthand syntax `[]`. These changes improve code readability and maintainability.
#1025 
This pull request includes several changes to the `KmpPrefixTrie` and `PrefixTrie` classes in the `Detection/src/Extensions` directory. The primary focus of these changes is to improve code readability and consistency by replacing null checks with a new `TrueIfNull` method and simplifying array initializations.
Improvements to null checks and array initializations:
* [`Detection/src/Extensions/KmpPrefixTrie.cs`](diffhunk://#diff-f7d7a6f255af7dae5d27beb7905984ef1d01f619d7228a2d6dbfecaa7549917bL89-R95): Replaced null checks with `TrueIfNull` method in multiple …
> Refactor null checks and collection initialization.

- Annotations/Directory.Build.props
- Cryptography/Directory.Build.props
- Detection/Directory.Build.props
- Domain/Directory.Build.props
- Extensions/Directory.Build.props
- Hosting/Directory.Build.props
- Mvc/Directory.Build.props
- Responsive/Directory.Build.props
- System/Directory.Build.props
- Testing/Directory.Build.props
- Tools/Directory.Build.props
- Validation/Directory.Build.props
- Webmaster/Directory.Build.props
- Webserver/Directory.Build.props
- sign.ps1
Bumped version prefixes for Validation, Annotations, and System projects to reflect new releases. Uncommented directory entries in `sign.ps1` to enable signing for System, Validation, and Annotations. These changes prepare the projects for upcoming builds and releases.
> Update version prefixes and uncomment signing directories

- Domain/Directory.Build.props
This change adds the `VersionSuffix` property with the value "Beta-1" to the Domain project. This helps in identifying the release as a pre-release version and improves versioning clarity for package management systems.
> Set VersionSuffix to Beta-1 in Domain project

- .github/workflows/dotnet.yml
- .github/workflows/qodana_code_quality.yml
- .github/workflows/qodana_dotnet.yml
- Wangkanai.slnx
Reordered Coverlet parameters in dotnet.yml for better clarity and updated the artifact path in qodana_code_quality.yml to use runner.temp for improved compatibility. These changes ensure consistent and reliable handling of coverage data.
> Update workflows for code coverage output handling

- .github/workflows/qodana_dotnet.yml
The `--apply-fixes` argument has been removed to prevent automatic code fixes during the Qodana scan. This ensures changes are reviewed before being applied, improving workflow robustness and code quality control.
> Remove auto-fix application from Qodana workflow.

- .github/workflows/qodana_dotnet.yml
- Directory.Build.targets
- qodana.yaml
Corrected the upload-artifact path to avoid unnecessary asterisks and ensure proper coverage data upload. This change improves the reliability of the Qodana scan process.
> Fix artifact upload path in Qodana workflow

- .editorconfig
- Domain/src/AuditTrail.cs
- Domain/src/Primitives/Error.cs
- Domain/src/Primitives/Result.cs
- Domain/src/Properties/AssemblyInfo.cs
- Domain/tests/Primitives/ErrorTests.cs
- Domain/tests/Primitives/ResultTests.cs
This pull request introduces two new classes, `Error` and `Result`, to the `Domain/src/Primitives` directory. These additions provide a structured way to represent domain errors and operation results, enhancing error handling and result management across the codebase.
* **`Error` Class**:
- Represents a domain error with a `Code` and `Message` property.
- Includes a static `None` instance for representing no error.
- Supports implicit conversion to a string using the `Code` property.
* **`Result` Class**:
- Encapsulates the outcome of an operation, with properties for `IsSuccess`, `IsFailure`, and an associated `Error`.
- Provides static factory methods for creating success and failure results, including generic versions for results with values (`Result<TValue>`).
- Includes utility …
> Add Error and Result primitives for domain operations

- Directory.Build.targets
This change restricts the Microsoft.SourceLink.GitHub package reference to the DEBUG build configuration. It ensures the package is not included in other configurations, optimizing build behavior.
#1069 Source link is appearing as a dependency
> Set SourceLink package reference for DEBUG configuration only

- Detection/src/Services/BrowserService.cs
- Detection/tests/Services/BrowserServiceTests.cs
While using Edge and Firefox the library incorrectly reports Browser.Safari rather then Browser.Edge and Browser.Firefox
User Agents tested with (reported from 2 of our lab-phones) 
Edge: Mozilla/5.0 (iPhone; CPU iPhone OS 18_3_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) EdgiOS/135.0.3179.98 Version/18.0 Mobile/15E148 Safari/604.1 
Firefox: Mozilla/5.0 (iPhone; CPU iPhone OS 18_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) FxiOS/138.0  Mobile/15E148 Safari/605.1.15
Fixes #1066
> [Detection] Fix for Incorrect Browser reported for Edge and Firefox on iOS

- Analytics/Directory.Build.props
- Annotations/Directory.Build.props
- Blazor/Directory.Build.props
- Cryptography/Directory.Build.props
- Detection/Directory.Build.props
- EntityFramework/Directory.Build.props
- Extensions/Directory.Build.props
- Federation/Directory.Build.props
- Hosting/Directory.Build.props
- Identity/Directory.Build.props
- Markdown/Directory.Build.props
- Microservice/Directory.Build.props
- Microservice/README.md
- Mvc/Directory.Build.props
- Responsive/Directory.Build.props
- Security/Directory.Build.props
- Solver/Directory.Build.props
- System/Directory.Build.props
- Tabler/Directory.Build.props
- Testing/Directory.Build.props
- Tools/Directory.Build.props
- Validation/Directory.Build.props
- Webmaster/Directory.Build.props
- Webserver/Directory.Build.props
- build.ps1
- sign.ps1
Rolled back version prefixes for multiple Wangkanai components to previous values. This ensures alignment with project versioning policies and standardizes the release management process across the repositories.
This pull request includes version downgrades across multiple modules in the Wangkanai project. The changes primarily involve reducing the `VersionPrefix` in `Directory.Build.props` files for various components, such as `Analytics`, `Blazor`, `Cryptography`, and others. These downgrades appear to align with a broader versioning strategy or rollback.
* **Analytics**: Downgraded `VersionPrefix` from `2.2.0` to `2.1.0` in `Analytics/Directory.Build.props`.
* **Blazor**: Downgraded `VersionPrefix` from `4.2.0` to `4.1.0` in `Blazor/Directory.Build.props`.
* **Cryptography**: …
> Reduce version prefixes across all projects.

- Domain/Directory.Build.props
Updated the VersionSuffix property in Directory.Build.props from Beta-3 to Beta-4 to reflect the new pre-release iteration. This ensures proper versioning semantics for the project.
> Update VersionSuffix to Beta-4 in Domain build props

- Analytics/sign.ps1
- Annotations/sign.ps1
- Blazor/sign.ps1
- Cryptography/sign.ps1
- Detection/sign.ps1
- Domain/sign.ps1
- EntityFramework/sign.ps1
- Extensions/sign.ps1
- Federation/sign.ps1
- Hosting/sign.ps1
- Identity/sign.ps1
- Markdown/sign.ps1
- Microservice/sign.ps1
- Mvc/sign.ps1
- Nation/sign.ps1
- Responsive/sign.ps1
- Security/sign.ps1
- Solver/sign.ps1
- System/sign.ps1
- Tabler/sign.ps1
- Testing/sign.ps1
- Tools/sign.ps1
- Validation/sign.ps1
- Webmaster/sign.ps1
- Webserver/sign.ps1
- sign.ps1
Introduced a new `$skip` parameter to allow skipping version updates. Updated logic to check for `$skip` instead of `$update` when deciding to skip version changes. This enhances flexibility in the script's usage.
This pull request introduces a new `skip` parameter to the `sign.ps1` script, allowing users to bypass version updates. The changes include adding the parameter and modifying the logic to handle it.
**New Parameter Addition:**
* Added a `[bool]$skip` parameter to the `sign.ps1` script to provide an option for skipping version updates.
**Logic Update:**
* Replaced the condition checking for `!$update` with `$skip` to implement the new skip functionality. When `$skip` is true, the script outputs a message and exits without performing a version update.
> Add skip parameter to bypass version update

- Nation/Directory.Build.props
Incremented the version prefix from 0.0.0 to 0.1.0 in Directory.Build.props. This reflects progress towards a new release and aligns with ongoing development updates.
> Update version prefix to 0.1.0

- Domain/src/Stores/AuditStore.cs
- Domain/src/Stores/IAuditStore.cs
- Domain/src/Stores/IQueryableAuditStore.cs
This pull request involves a renaming and refactoring effort to simplify and standardize naming conventions for audit-related classes and interfaces in the `Wangkanai.Domain.Stores` namespace. The changes primarily focus on replacing "AuditTrail" with "Audit" in class and interface names while maintaining functionality. Below are the key changes:
* `Domain/src/Stores/AuditTrailStore.cs` was renamed to `Domain/src/Stores/AuditStore.cs`, and the class name was updated from `AuditTrailStore` to `AuditStore`. Additionally, the implemented interface was updated from `IQueryableAuditTrailStore` to `IQueryableAuditStore`.
* `Domain/src/Stores/IAuditTrailStore.cs` was renamed to `Domain/src/Stores/IAuditStore.cs`, and the interface name was updated from `IAuditTrailStore` to `IAuditStore`. The …
> [Domain] Audit Store for improved naming consistency across the domain

- Hosting/Directory.Build.props
- Hosting/sign.ps1
This pull request modifies the `Hosting/sign.ps1` script to fix the conditional logic for skipping updates during the packaging process.
Key change:
* Corrected the conditional statement in the `Hosting/sign.ps1` script to check for the negation of the `$publish` variable (`if (!$publish)`), ensuring that updates are skipped only when `$publish` is `false`.
> Increment VersionPrefix to 3.5.0 and adjust sign.ps1 logic to skip update when `$publish` is false

- Annotations/tests/NegativeIntegerAttributeTests.cs
- Annotations/tests/PositiveIntegerAttributeTests.cs
- Annotations/tests/ZeroIntegerAttributeTests.cs
This pull request simplifies the `NegativeIntegerAttributeTests` class by removing unused test methods and redundant code. It also cleans up the `NegativeInteger` class by eliminating commented-out methods related to unused attributes.
Changes to `NegativeIntegerAttributeTests`:
* Removed the `Parameter_Attribute_Message` and `Parameter_Attribute_Error` test methods, which were commented out and unused.
* Removed assertions and expected values related to the `Message` property in the `Parameter_Attribute_Exist` test method.
Changes to `NegativeInteger`:
* Deleted commented-out methods `ParameterMessage` and `ParameterError` that were not actively used.
> [Annotations] Remove commented and unused test cases

- .github/workflows/dotnet.yml
This pull request updates the `.github/workflows/dotnet.yml` file to improve the CI/CD pipeline by reorganizing SonarCloud and code coverage setup steps and switching to the `dotnet-coverage` tool for collecting test coverage data.
* Reorganized SonarCloud setup: Renamed the step to "Setup SonarCloud" and moved the SonarCloud scanner step to follow npm installation for better logical grouping.
* Added a new step for setting up `dotnet-coverage`: Installed the `dotnet-coverage` tool globally for collecting test coverage data.
* Updated test coverage collection: Replaced the `dotnet test` command with `dotnet-coverage collect` to generate coverage data in XML format.
> [CI] dotnet-coverage global tool

- Annotations/src/NegativeIntegerAttribute.cs
- Annotations/src/PositiveIntegerAttribute.cs
- Annotations/src/ZeroIntegerAttribute.cs
- Annotations/tests/ZeroIntegerAttributeTests.cs
This pull request updates the behavior and tests for the `ZeroIntegerAttribute` in the `Annotations` project. The most important changes include modifying the attribute's inheritance behavior, adding new tests to validate this behavior, and updating the derived class implementation to explicitly handle attributes.
* [`Annotations/tests/ZeroIntegerAttributeTests.cs`](diffhunk://#diff-b3d4af9ce0e75910404774f17b81f4888cd8ca052bf173631df4dee8c527a409L80-R132): Updated the test `Attribute_Is_Inherited` to `Attribute_Is_Not_Inherited` and changed the assertion to reflect that the `ZeroIntegerAttribute` is no longer inherited (`AttributeUsage.Inherited` is set to `false`).
* `Annotations/tests/ZeroIntegerAttributeTests.cs`: Added tests to validate that derived class properties and methods do not …
> [Annotations] Attribute inheritance

- SonarQube.Analysis.xml
This pull request includes a small change to the `SonarQube.Analysis.xml` file. The change comments out the `sonar.branch.name` property, which was previously set to `main`.
> [CI] Comment out `sonar.branch.name` property in SonarQube.Analysis.xml

- .editorconfig
- System/src/Checks/NullEqualityComparerExtensions.cs
- System/src/Checks/NullEqualityExtensions.cs
- System/src/Collections/RandomAccessQueue.cs
- System/src/Decorator.cs
- System/src/Extensions/DictionaryExtensions.cs
- System/src/Math.cs
- System/src/StaticRandom.cs
- System/tests/Checks/NullEqualityTests.cs
This pull request introduces a new utility class `NullEqualityComparerExtensions` to simplify null and default value checks, and updates existing code in `RandomAccessQueue` to leverage this new functionality for improved readability and maintainability.
* [`System/src/Checks/NullEqualityComparerExtensions.cs`](diffhunk://#diff-4dc1cdff26dcd760ed42ad0f5cce4db1087055fa6b05443ef54c851dc8479af5R1-R21): Added a static class `NullEqualityComparerExtensions` with two extension methods, `EqualNull` and `NotNull`, to determine whether a value is null or the default value of its type.
* [`System/src/Collections/RandomAccessQueue.cs`](diffhunk://#diff-0819155482bc46e0c2e294b475ab624828a5e5a11849ed15c65ef7fec3e24504L377-R377): Updated the `BinarySearch` method in `public IEnumerator<T> …
> [System] Introduce `EqualNull` and 'NotNull'

- System/src/Collections/RandomAccessQueue.cs
- System/src/Constants.cs
- System/src/Reflection/PropertyCopy.cs
- System/src/Resources/AnnotationResources.cs
- System/src/Resources/ExceptionResources.cs
- System/src/Resources/ObsoleteResources.cs
- System/src/Resources/SystemResources.cs
- System/src/StaticRandom.cs
- System/tests/Checks/NullEqualityTests.cs
- System/tests/Reflection/PropertyCopyTests.cs
This pull request updates the `System/tests/Checks/NullEqualityTests.cs` file to improve nullability handling by using the null-forgiving operator (`null!`). Additionally, it disables specific ReSharper warnings to enhance code readability and maintainability.
* Updated test cases to use the null-forgiving operator (`null!`) for `string` and `TestClass` variables, ensuring compatibility with nullable reference types and avoiding unnecessary compiler warnings. [[1]](diffhunk://#diff-9ffaf49e54f6618cfb6892137ca5d67bdf262650b0c4a4b2c7188ad01acb12ddL12-R14) [[2]](diffhunk://#diff-9ffaf49e54f6618cfb6892137ca5d67bdf262650b0c4a4b2c7188ad01acb12ddL128-R130) [[3]](diffhunk://#diff-9ffaf49e54f6618cfb6892137ca5d67bdf262650b0c4a4b2c7188ad01acb12ddL244-R246) …
> [System] Use nullable reference syntax in `NullEqualityTests` 

- build.ps1
- sign.ps1
This pull request updates the list of project directories in both the `build.ps1` and `sign.ps1` scripts. The changes primarily reorder and remove certain directories, ensuring that only relevant components are included for build and signing operations.
Directory list updates:
* In `build.ps1`, the `Domain`, `EntityFramework`, and `Analytics` directories are removed, and the remaining directories are reordered to prioritize `Mvc`, `Webserver`, `Webmaster`, `Detection`, and `Responsive` after `Tools`.
* In `sign.ps1`, the commented-out directory list is updated to match the new order, removing `Domain`, `Audit`, `EntityFramework`, and `Analytics`, and reordering the remaining entries for consistency.
> refactor: remove Domain and Audit entries from build and sign scripts
